### ISSUE TITLE
Make it possible to overwrite Services when using UseStartup

### ISSUE THREAD

**Issue by tlbdk** [aspnet/Hosting#1012]
I'm integration testing my project with TestServer and would like to overwrite some of the dependencies when running the unit test:

// TestBase.cs

```
var builder = new WebHostBuilder()
                .ConfigureLogging(factory =>
                {
                    factory.AddProvider(_inMemmoryRequestLoggerProvider);
                })
                .UseStartup(typeof(Startup), (services) =>
                {
                    // Runs after the ConfigureServices in Startup.cs but before Configure
                    var fakeSMSClient = new FakeSMSClient();
                    services.AddSingleton<ISMSClient>(fakeSMSClient); // Overwrite "production" version of ISMSClient
                });
_testServer = new TestServer(builder);
```

I have copy/pasted and patched the current code to support this, but I would be nice if it was possible out of the box, I can do a pull if it would be accepted or do you have another approach for doing this?

**Comment by muratg** [comment]
We'll look into how/if this can be done

**Comment by tlbdk** [comment]
I could do a pull request if you like the interface of adding another parameter to .UseStartup(). I'm already using this in my project and it has been quite useful to be able to overwrite dependencies from unit tests.

**Comment by davidfowl** [comment]
@tlbdk We'd like to design something more wholistic than a boolean. I'm going to play around and see if we can add something more first class.

**Comment by tlbdk** [comment]
@davidfowl boolean? Right now I have added a delegate the injects the IServiceCollection as this seems to be the pattern.

**Comment by davidfowl** [comment]
Ah I misread that. What's the name of that interface?

**Comment by tlbdk** [comment]
public static IWebHostBuilder UsePatchStartup(this IWebHostBuilder
hostBuilder, Type startupType, Action<IServiceCollection>
customConfigureServices = null)

But I could do a pull to add this to UseStartup as it's a fairly simple
change?

**Comment by davidfowl** [comment]
That doesn't look very clear or user friendly. Maybe we can add something like a startup filter that also handles services (or maybe we can extend IStartupFilter in 2.0 to also handle services). IMO that, would be a more obvious pattern that gels with our existing APIs rather than another method on the WebHostBuilder.

Another way to potentially solve this is by adding services based on the environment and then setting up a `"Testing"` environment.

**Comment by tlbdk** [comment]
Have not looked at the IStartupFilter, will do that this week. But just to
explain why I'm doing it this way. Right now I'm testing some error cases
by injecting a controller that has endpoints for each test case, I don't
really want this to be part of my app code. In general I think it's a lot
nicer to be able for the test to inject it's setup and configuration so the
app project has zero dependencies required just for testing.

**Comment by davidfowl** [comment]
Since we're not going to break `IStartupFilter` in 2.0.0, we need to introduce a new interface for this. `IConfigureStartupServices`:

```C#
public interface IConfigureStartupServices
{
    Action<IServiceCollection> Configure(Action<IServiceCollection> next);
}
```

This method can be used to run code around (before or after) the ConfigureServices method in the `IStartup` implementation. I'm not sure that we need to make this async but we are giving making Startup.Configure the ability to run async in 2.0 (food for thought).

**Comment by davidfowl** [comment]
With this design, it isn't critical to do it for 2.0.0, we can move this to 2.1.

**Comment by kazha** [comment]
How it is possible to override anything else besides services by using ConfigureTestServices?
AddDbContext (to override and use inmemmory db) does nothing and to AddMiddleware for unittests you still have to override whole startup config.

**Comment by javiercn** [comment]
@kazha Create and use a specific environment just for integration testing purposes and fork the pipeline appropriately the same way we do for development.

**Comment by kazha** [comment]
@javiercn that is one solution, but it is not good enough, I don't want to add additional logic and env just because of unit tests. That stuff should be kept at unit test level. On previous version I was able to do that by overriding Startup methods within unit test Startup. Now, from what I understand, I have to actually change functionallity on service itself to test it. It does not sound to me as a correct solution. 
If i can override services on unit tests why dbContexts and middlewares ar left out?
Before I was using [these](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/test/ServicesTests/Application.FunctionalTests/Services/Basket) samples. New version unit test solution looks like a downgrade in functionality to me, am I missing something?

**Comment by javiercn** [comment]
> On previous version I was able to do that by overriding Startup methods within unit test Startup.

Not sure what this means. 
* What was possible before that is not possible now?
* Can you clarify exactly what you are trying to achieve? Can you provide an explicit example? Is it overriding the DbContext for test purposes? If so, what exactly about it. The DbProvider?

**Comment by kazha** [comment]
So before, in 2.0 core it was like this
Service had a startup class that included 
public void ConfigureServices(IServiceCollection services)
in which I was able to call virtual method OnConfigureServices(services) that I've had created
that added db context services.AddDbContext<DbContext>(options);
in unit tests I was able to override the OnConfigureServices method and AddDbContext as inmemory.
Same goes with AddMiddleware, I created virtual method that could be overriden and in unit tests I could add middlewares for specific purpouses, not interfering with actual functionality, that has to be done now.
So before
``` 
public abstract class MyStartup
{
    protected virtual void OnConfigureServices(IServiceCollection services)
    {
        services.AddDbContext<MyDbContext>(options =>
        {
            options.UseSqlServer(_serviceConfiguration.ConnectionString);
        });
    }
    public void ConfigureServices(IServiceCollection services)
    {
        OnConfigureServices(services);
    }
}
```
and in unit tests
```
public abstract class MyTestStartup : MyStartup
{
    protected override void OnConfigureServices(IServiceCollection services)
    {
        services.AddDbContext<MyDbContext>(options =>
        {
            options.UseInMemoryDatabase("InMemoryDbForTesting");
        });
    }
}
```
and as described in [functionaltests](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/test/ServicesTests/Application.FunctionalTests/Services/Basket/BasketTestsStartup.cs) I was able to add middleware by overriding
protected override void ConfigureAuth(IApplicationBuilder app) 
and adding AuthMiddleware, but now there is no way to do that with WebApplicationFactory within core 2.1, (or I am failing to find the way to do that)
all I can do is override whole ConfigureServices, that is no good, or add some additional logic to actual service, that is no good either .

My point is, there should be a way to override AddDbContext, or atleast options property,
and AddMiddleware for unit tests, and to do that I should not change actual service logic.
If I am still not making myself clear, I can come up with code that is more detailed sample and provide it.

**Comment by javiercn** [comment]
@kazha What is failing in the above code in 2.1? That should still be possible and work. You can configure the host for testing purposes in the same way by overriding ConfigureServices on WAF and calling UseStartup and passing in your custom startup class.

In addition to that, you can always configure the DbContext on the host container (by calling WebHostBuilder.ConfigureServices (will execute before startup configure services) and using an IStartupFilter to configure middleware before and after the ones in your pipeline.

The only case where you need to use a custom startup class is if you need to inject code within the middleware pipeline. And again, that's why we recommend using a custom environment for Integration tests.

**Comment by kazha** [comment]
@javiercn 
1. I cannot create custom startup anymore as described [here](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) I have to use SUT's Startup. Otherwise tests won't work
2. ConfigureServices overrides whole configuration, I don't whant to do that. As then I have to replecate configuration and track changes, and there is too much room for error.
3. As I mentioned before I cannot use ConfigureTestServices cos it only overrides services and does not do that for DbContext
4. And for env, I understand that that is a way, but  I don't want to interfere with existing functionality and add specific env for unit tests and additional logic. Before I was able to do that, not anymore.

**Comment by davidfowl** [comment]
> As I mentioned before I cannot use ConfigureTestServices cos it only overrides services and does not do that for DbContext

I'm confused why this doesn't work. It was made specifically for overriding services.

**Comment by kazha** [comment]
@davidfowl perhaps I am doing it wrong?
```
 builder.ConfigureTestServices(services =>
{
      //These are overriden
      services.AddSingleton(new FakeEventBusConnection());
      services.AddSingleton<IEventBus, FakeEventBus>(s => new FakeEventBus(s));
     //this does not work
    services.AddDbContext<MyDbContext>((provider, options) =>
   {
    options.UseInMemoryDatabase("InMemoryDbForTesting");
   });
}
```

also tryed AddEntityFrameworkInMemoryDatabase() on services as well no good

**Comment by javiercn** [comment]
ConfigureTestServices works. https://github.com/aspnet/Identity/blob/master/test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs

Overriding the database storage is something we do in the Identity functional tests. See how we do it on the link aboce

**Comment by xaviergxf** [comment]
Why can't we inject directly the Startup instance, instead of the type? I do the same as @kazha creating a TestStartup, but since i cannot create it manually i cannot for ex set the ITestOutputHelper to replace Logging with Xunit's.

```
public class TestStartup : Startup
{
        public ITestOutputHelper Output { get; set; }
        public TestStartup(IConfiguration configuration) : base(configuration)
        {
        }
}
```

**Comment by kazha** [comment]
@javiercn Sorry for late answer, time was not on my side, so couldn't deal with this.
The sample is fine, but not in my case.
Sample uses builder.ConfigureServices(sc => sc.SetupTestDatabase<TCo....
and as I said, it overrides everything. As of now I just check Environment for "test" env, as it is simplest way, otherwise it is too much of a hassle. Thanks anyways! Though I still think that ConfigureTestServices should override AddDbContext as well. I will look into options pattern as described [here]([url](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1)) as it seems to have solution I seek.

**Comment by APIWT** [comment]
@kazha We were able to do this by using the following. Hope this helps!

```csharp
var client = factory.WithWebHostBuilder(builder =>
    builder.ConfigureTestServices(
        services =>
        {
            var dbOptions = new DbContextOptionsBuilder<SomeDbContext>()
                .UseInMemoryDatabase("InMemoryDbTestName")
                .Options;
            var dbContext = new SomeDbContext(dbOptions);

            dbContext.Database.EnsureDeleted();

            // go ahead and seed your dbContext here (don't forget to call SaveChanges)

            services.AddScoped(provider => dbContext);
        })).CreateClient();
```

At first we were actually just adding our repository services but this is a lot easier and it allows for DI to "just work".
