### ISSUE TITLE
Make the HostContext available to extension methods on IWebHostBuilder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1014]
Today it's impossible to get at the `HostingContext` as an extension method on `IWebHostBuilder`, this means you can't flow the `IHostingEnvironment` in your extension methods that hang off the builder.

/cc @JunTaoLuo @glennc

**Comment by glennc** [comment]
I was thinking of a couple of things around this:

1. promote WebHostBuilderContext to abstractions and have it as a property of the builder
1. provide a `UseServices` extension that has both `WebHostBuilderContext` and `ServiceCollection`. So that at least extensions that are just adding services can do it trivially.

What do you think of those?

**Comment by davidfowl** [comment]
I don't think we need 2 types (maybe that was a typo?).  `UseServices` shouldn't be required to get access to the host context, and it should be called `ConfigureServices` right?

**Comment by JunTaoLuo** [comment]
Thanks @glennc  for the PR https://github.com/aspnet/Hosting/pull/1020
