### ISSUE TITLE
Suggestion: a UseStartup<T>(args[]) overload like UseMiddleware

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Hosting#1146]
This would be very useful for instance when setting up a TestServer (TestHost namespace). 

Here I often want to inject some changes into a normal startup class (which could be anything from a mock startup just for testing or your production one)

**Comment by davidfowl** [comment]
Why can't you just use ConfigureServices to add services?

**Comment by NinoFloris** [comment]
Same reason use middleware has it, convenience.  

I want to close over a primitive value for the action lambda that's the constructor argument of a startup filter that I add as a singleton. This would be aweful to do through DI, have to make an IOptions class etc etc, all to just get such a small thing working

Besides having that lambda outside startup would be the last resort

**Comment by davidfowl** [comment]
> Same reason use middleware has it, convenience.

Not quite convenience. It was originally because of katana, there was no built in DI and no concept of named options so it was possible to have multiple pieces of middleware with different options, specifically authentication middleware needed this. We used to pass options directly to middleware but we've since standardized on using the DI system to do this via IOptions.

> I want to close over a primitive value for the action lambda that's the constructor argument of a startup filter that I add as a singleton.

Then add a custom `IStartup` with a delegate to the container or don't pass a primitive value just create a type and inject that. I don't think this is common enough to justify adding this method. 

Can you show an example of what you're actually trying to close over?

**Comment by muratg** [comment]
Closing this one.  @NinoFloris if you have more data and a scenario that you need to enable, please let us know.
