### ISSUE TITLE
WebHostBuilder.ConfigureAppConfiguration doesn't allow me to override CreateDefaultBuilder 

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Hosting#1170]
The current implementation of ConfigureAppConfiguration doesn't override CreateDefaultBuilder's configuration so that there isn't a way to have my configuration added before AddEnvironmentVariables. So that unless I go back to the old CreateBuilder style of creating a WebHost, I can't control the order of the configuration files.

If the IConfiguration had a clear() method that would be enough for me, but I don't understand why calling ConfigureApPConfiguration doesn't override, but instead adds more configuration. 

Please set me straight, I'm probably missing something.

**Comment by davidfowl** [comment]
> If the IConfiguration had a clear() method that would be enough for me.

It does! https://github.com/aspnet/Configuration/issues/680#issuecomment-311857606. You can call.

```C#
webHostBuilder.ConfigureAppConfiguration(builder =>
{
   builder.Sources.Clear();
});
```

> but I don't understand why calling ConfigureAppConfiguration doesn't override, but instead adds more configuration.

This was done specifically so that other components can *add* to the existing configuration. Consider a scenario where the host wants to light up behavior based on the environment you're running in. As an example, imagine when you were running in docker we automagically added the docker secrets provider.

**Comment by shawnwildermuth** [comment]
D'oh, I was still using Preview2. Works perfectly in RTM.
