### ISSUE TITLE
Reconcile conflicts between types in Microsoft.Extensions.Hosting and Microsoft.AspNetCore.Hosting

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1218]
We have a few types that overlap between the 2 hosting models and we need to decide what the long term and short term plans are:

- IHostingEnvironment
- IApplicationLifetime

A few options:
- We could add the Hosting.Extensions versions of these to the container of the WebHost and gradually change all of the libraries to use the new interfaces. This allows both systems to work side by side so we can do the gradual change over.

/c @glennc @Tratcher

**Comment by muratg** [comment]
@davidfowl Anything you'd like to do in 2.x timeline?  Otherwise this mostly looks like breaking changes that we can only do in 3.0.

**Comment by davidfowl** [comment]
@muratg no I'd like to do something in the 2.x timeline. There doesn't need to be any breaking changes here.

**Comment by muratg** [comment]
@davidfowl so do you want to copy some of the interfaces to MEH from MAH and start using them? If these are exposed on any public API, that is a breaking change, right?  Do you have a picture of what you want in your mind?

**Comment by davidfowl** [comment]
@muratg I sent a PR 😄

**Comment by alexk8** [comment]
@davidfowl , 
Sorry guys, I'm a simple dev, and I dont understand why this issue was closed, the conflict (kind of) leaked into 2.1 release.... We now have two not-interchangable IHostingEnvironment. Why do we have a duplicate, not an extension? I propose a fix:
```
namespace Microsoft.AspNetCore.Hosting
{
    public interface IHostingEnvironment : Microsoft.Extensions.Hosting.IHostingEnvironment
    {
        string WebRootPath { get; set; }
        IFileProvider WebRootFileProvider { get; set; }
    }
}
```
Do you find it appropriate?

**Comment by davidfowl** [comment]
What does this fix?

**Comment by alexk8** [comment]
This fixes a confusing code duplication, and particularly needed for this:
```
            var builder = new WebHostBuilder()
            .ConfigureAppConfiguration((ctx, cfgBld) =>
            {
                var env = ctx.HostingEnvironment;
                // here, I needed Microsoft.Extensions.Hosting.IHostingEnvironment, but get Microsoft.AspNetCore.Hosting.IHostingEnvironment

                // this works, but isn't a safe cast
                var env2 = (Microsoft.Extensions.Hosting.IHostingEnvironment)env;

                //now I can use env2
            });
```

**Comment by Tratcher** [comment]
What do you need the Extensions version for? It's not providing any new functionality.

**Comment by alexk8** [comment]
@Tratcher , @davidfowl 
Particularly...
The case is that all my (as an examlpe) buisnes-logic resides in class-library indepent of huge bunch of AspNetCore stuff  and still needs IHostingEnvironment to do some setup based on (dev/prod/other) conf. And only then it's used inside webapp (and not only webapp)... 
Generally... 
Well, why Extensions.Hosting has appeared anyway? I thought it emerged because of decoupling, decomposition and other "desing" principles... I think it this shouldnt be left half-way...

**Comment by davidfowl** [comment]
Yes, we can do what you suggest, we're a bit of a 1/2 state right now because the more generic host came after the web host. I don't think we envisioned people passing the IHostingEnvironment instance resolved from the web application to an API that took the more generic version. What we tried to account for was the implementation being available on both hosting so that it enables you to write generic logic that can be used in both hosting APIs (i.e. you can inject the Extensions.Hosting.IHostingEnvironment when running on the IWebHostBuilder or the IHostBuilder)

Are you currently using the generic host or are you writing web applications?

**Comment by alexk8** [comment]
Yes, platrofm can inject any of them, but only if DI-container has been initialized... In the code above it isn't exist yet. I'm still quite convinced than two nearly identical interfaces shouldn't exist side-to-side at all...
My case (when I stumbled over this) is because I try to use decoupling in my code... In general I'm writing webapp, but i have separated shared code, which is also used in console-tools, console-hosted functional tests. But my gereral argument is that two indepentent nearly identical interfaces shouldnt exist. One of them is more general, one - specialized, so there must be an inheritance, IMHO.
I sertainly can live without it, but I hope this will be changed if it will not going to brake anything

**Comment by davidfowl** [comment]
No I think this is a reasonable thing to do in 2.2.

**Comment by davidfowl** [comment]
I'll open a new issue.
