### ISSUE TITLE
Dreaded ErrorCode = '0x80070002 on IIS

### ISSUE THREAD

**Issue by Vlaaaaaaad** [aspnet/Hosting#1234]
Hi,

I am trying to run an NET Core 2.0 application on IIS 10, running on Windows Server 2016, but when trying to run it, I get ``HTTP Error 502.5 - Process Failure`` page. In Event Viewer I get ```Application 'MACHINE/WEBROOT/APPHOST/BLA-WEBAPI' with physical root 'C:\Websites\BLA\BLA-WebAPI\' failed to start process with commandline 'dotnet .\BLA.WebAPI.dll', ErrorCode = '0x80070002 : 0.```

Weird thing is that when I run ``dotnet .\BLA.WebAPI.dll`` from Powershell the app works.

I ran through all the issues in https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x, resterted the server multiple times and nothing. I did set ``stdoutLogEnabled="true"`` and files are created, but empty.

Any ideas where I should look next? Are there more verbose logs for IIS somewhere?

**Comment by Vlaaaaaaad** [comment]
The Identity for the application pool was at fault.

**Comment by mac10688** [comment]
I am having the same issue. What was wrong with the Identity for the application pool?

**Comment by Vlaaaaaaad** [comment]
The issue for me **I think** was the fact that the sites were in a non-standard location and IIS did not have read rights to that folder. I crankily changed the application pool to run as Administrator and everything worked.

**Comment by mac10688** [comment]
Ah ok. In my case, the IIS wasn't configured correctly. Infrastructure says that enabling directory browsing or url authorization fixed it for us. He doesn't know which and he didn't care to find out which one. Hopefully this will help someone else who happens upon this page like I did.

**Comment by jdownie** [comment]
Man! I finally worked this one out (in my instance) and I found that `web.config` had `processPath="dotnet"`. I had to go into `cmd.exe` to run `where.exe`  (because that means something else in powershell now) and located dotnet in `C:\Program Files\dotnet\dotnet.exe`. I then set `processPath="C:\Program Files\dotnet\dotnet.exe"` and voila! Mind you, I had changed about 500 other things trying to work it out, so there might have been other factors at play. Just posting what I found FWIW.

**Comment by vketsenko** [comment]
@jdownie, thanks, you solution works, had the same issue. Turned out restart helps to fix this, probably IIS needs restart to update the paths, otherwise it can't find dotnet.exe

**Comment by Gordon-Beeming** [comment]
@jdownie your solution works for me too. Only question I have is how we can set that path during a deploy or even in the deploy output. 

Currently I'm running where on deploy and then replacing the value in the web.config but it's not ideal :(

**Comment by Gordon-Beeming** [comment]
I rebooted and didn't come onto the app pool identity path =(, simple script that just checks the machine paths and then sets the variable at deploy time sorted it for me until I can investigate more =P. 

https://beeming.net/just-coding/2018/5/how-do-i-fix-http-error-5025-process-failure-when-hosting-in-iis-with-dotnet-core

**Comment by Baffour** [comment]
I don't know why rebooting didn't work for you @Gordon-Beeming , but for anyone else that comes across this issue, I was able reload the path using the iisreset command. That would save you the hassle of rebooting, which is especially annoying if you're doing automated deployments/provisioning

**Comment by john-t-garrard** [comment]
I began getting this same error when we moved from Windows Server 2016 to Windows Server 2012 R2 - initially, when we copied the application from 2016 to 2012 R2 it ran fine - but then we published using VS 2017 v15.7.5 and ran into this error. (Deployment Mode = Framework-Dependent)

Our problem was in the Application Pool settings - in Advanced we had "Load User Profile" set to False (the default is True) - not sure why it was set that way, but when I set it to True, the web app loaded successfully.  (BTW, running using Identity = ApplicationPoolIdentity)

Hope this helps someone else out there.

**Comment by autukill** [comment]
> The issue for me **I think** was the fact that the sites were in a non-standard location and IIS did not have read rights to that folder. I crankily changed the application pool to run as Administrator and everything worked.

this is work for me! 

**Set "Identity " to "Administrator"**

I have encountered this problem when running asp.net core on Windows 2008 R2. It has been around for a while and it has been bothering me.

When I was unable to upgrade to dotnet 2.2 today, I encountered this problem when reinstalling 2.1, because the website could not start properly, so I had to spend a whole day looking for a solution.

If no return value when powershell execute "dotnet ./MyWebApplication.dll". You can try **the powershell with administrator privileges to execute "dotnet ./MyWebApplication.dll".**

Below is my "web.config" content (framework dependent, dotnet 2.1):
`<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments=".\MyWebApplication.dll"  stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>`
