### ISSUE TITLE
Guidance on how to deploy an already running app

### ISSUE THREAD

**Issue by flipdoubt** [aspnet/Hosting#1270]
Can someone point me to the official guidance on how to deploy an already running app when running dotnet behind either IIS or NGINX? I've searched, of course, and found all kinds of references to `app_offline.htm`, but that means nothing on Linux or Mac or when simply debugging with `dotnet run`.

**Comment by Tratcher** [comment]
This is really deployment specific. The app_offline.htm trick works because the IIS launcher (AspNetCoreModule) listens for the file and kills your app.

Having something listen for a signal and shut down your app is the easy part. Keeping it from restarting your app until you're ready, and sending something meaningful to your clients in the meantime is where things get harder.

The `dotnet run` dev loop is an interesting special case. Several people have reported success by combining `dotnet watch` with `dotnet run` to run their app and kill it whenever files changes so it can restart. However, there are no official docs on this scenario. @natemcmaster do you have any references?

**Comment by natemcmaster** [comment]
[dotnet-watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch) is a development tool. I wouldn't use it for deployments. dotnet-watch only restarts the server when \*.cs or \*.csproj files change. It doesn't have retry logic, support 'offline' responses when the app is down, or watch changes the \*.dll files.

**Comment by flipdoubt** [comment]
Where should I go to request/suggest this kind of guidance?

**Comment by Tratcher** [comment]
@shirhatti

**Comment by jstallm** [comment]
It really depends on your situation : Are you deploying to the cloud? on prem? just local? How many people are working on the solution?
There can be vastly different approaches to deployment based on these questions, and these needs to be clarified. 
if you are deploying to IIS, one option is to use powershell scripts/modules.

**Comment by jstallm** [comment]
It depends. for instance, you could be running a microservice architecture, and applications running on linux but managed through an orchestrator such as k8s.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
