### ISSUE TITLE
TestHost vs Kestrel differences

### ISSUE THREAD

**Issue by kimbell** [aspnet/Hosting#1282]
I have some ASP.NET Core 1.1 code that I'm upgrading to 2.0. During this process I encountered a problem with my middleware. It was using IOptionsSnapshot from the constructor. This ends up with a 
'Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot' based error. 

I got this error when running from Visual Studio. 

I also have tests for my code, so I updated them to cover both 1.1 and 2.0. In this code I'm using TestHost. I was hoping the tests for 2.0 would crash the same way as Kestrel, but all my tests are green.

Is this constraint verified in the TestHost? Should it be?

**Comment by khellang** [comment]
> This ends up with a 'Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot' based error.

That's because you have (at least) a bug in your code and now you're getting a warning about it :wink:

Just move the `IOptionsSnapshot<T>` down into your `Invoke` method (services injected in ctor is from application scope, while `Invoke` is request scope):

```csharp
public Task Invoke(HttpContext context, IOptionsSnapshot<MyOptions> options) { /* blah */ }
```

I'm assuming you're using `WebHost.CreateDefaultBuilder` in your production application? In 2.0, that method does some magic to [enable scope validation in a development environment](https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L183-L186). This is to prevent you from accidentally shooting yourself in the foot by creating memory leaks.

> Is this constraint verified in the TestHost?

[Looks like it isn't.](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L41)

When you wire up your `TestServer`, you're responsible for setting up the `IWebHostBuilder`, so you have to do (more or less) the same as `WebHost.CreateDefaultBuilder`.
If I were you, I'd call the same method as your production app (probably in `Program`) to set up the `WebHost` for your tests, so you get the exact same behavior in your integration tests.

> Should it be?

That's a good question. I'd say yes, but I wonder how you could enable that check inside `TestServer` before building the `WebHost`.

**Comment by khellang** [comment]
I guess there could be introduced a static method like this:

```csharp
public class TestServer
{
    public static TestServer Create(Action<IWebHostBuilder> configure)
    {
        var builder = new WebHostBuilder()
         // .UseEnvironment(EnvironmentName.Testing) <-- Would be a nice addition ;)
            .UseDefaultServiceProvider(o => o.ValidateScopes = true);

        configure(builder);

        return new TestServer(builder);
    }
}
```

That would allow you to "pre-configure" the web host builder before it's passed to the user for modification, in case the user wants to swap the default service provider.

**Comment by kimbell** [comment]
I'm down with why the error occurs and it's fantastic that we now get an error for this. It would be nice if this validation was default on for the TestServer implementation in 2.0; then we could figure out the errors before running them on Kestrel :)

I tried the UseDefaultServiceProvider tip and it works. You just need to know that you have to write the code. If you have tests that target multiple versions, the code gets uglier since the method doesn't exist before 2.0. 
```CS
#if NETCOREAPP2_0
                .UseDefaultServiceProvider(p => p.ValidateScopes = true)
#endif
```

**Comment by Tratcher** [comment]
Adding scope validation to TestServer sounds like a good idea. It can be added here:
https://github.com/aspnet/Hosting/blob/076e5fe6afdc8a3a683efd3d8c65434d2746353e/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L41

**Comment by khellang** [comment]
@Tratcher Won't that override an existing, user-specified service provider?

**Comment by Tratcher** [comment]
Hmm, it works in CreateDefaultBuilder because the user code runs after that and can replace it, but in TestServer the ordering is reversed. Fair point.

**Comment by khellang** [comment]
> but in TestServer the ordering is reversed. Fair point.

Yeah, that's why I suggested a static `Create` method taking a configure-delegate. That way, you could "seed" the builder before passing it to the user for overrides.

**Comment by Tratcher** [comment]
What about a `public static IWebHostBuilder CreateTestBuilder()`?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
