### ISSUE TITLE
Web hosting on android?

### ISSUE THREAD

**Issue by Slion** [aspnet/Hosting#1287]
Is web hosting implemented for android?
Is that question relevant to this project or rather its dependencies?

When I tried calling WebHostBuilder.Build it results in System.NotImplementedException: The method or operation is not implemented. The sample in question is running just fine on Windows 10 .NET Framework.

**Comment by muratg** [comment]
Android support for .NET Core is a community-driven effort, tracked here: https://github.com/dotnet/coreclr/issues/1097.

**Comment by AdamDotNet** [comment]
@muratg - I don't think webhosting on Android is tied to being able to build/run CoreCLR on Android. I've just tried running Asp.Net Core 2.1 preview 2 on Xamarin.Android 8.3 (Preview) with Visual Studio 2017 15.7 Preview 4.

```
private void StartWebServer()
{
    string documentRoot = Path.Combine(FilesDir.AbsolutePath, "www");

    IWebHostBuilder webHostBuilder = new WebHostBuilder()
        .UseKestrel(options =>
        {
            options.ListenAnyIP(8989);
        })
        .UseSockets()
        .UseContentRoot(documentRoot)
        .Configure(app =>
        {
            app.UseStaticFiles(new StaticFileOptions
            {
                // Note: this too will have to use a different file provider to avoid FileSystemWatcher
                FileProvider = new PhysicalFileProvider(documentRoot)
            });
        });

    webHostBuilder.Build().Start();
}
```

The root cause of the NotImplementedException is as follows:

- WebhostBuilder.Build calls BuildCommonServices, a private method, and that calls a public static extension method, Initialize. See [WebHostBuilder.cs](https://github.com/aspnet/Hosting/blob/0f131ac2459280c01f8a3c8d3592cb6e0363693c/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L262).
- Initialize is hard coded to require a ContentRootPath and instantiate a PhysicalFileProvider. See [HostingEnvironmentExtensions.cs](https://github.com/aspnet/Hosting/blob/0f131ac2459280c01f8a3c8d3592cb6e0363693c/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironmentExtensions.cs#L29).
- Finally, PhysicalFileProvider instantiates a FileSystemWatcher, which is not implemented in Mono.Android. See [PhysicalFileProvider.cs](https://github.com/aspnet/FileSystem/blob/e632f4906e4464907f9f569bc2c2dbc2ae912e7c/src/FS.Physical/PhysicalFileProvider.cs#L78).

If there was some way to pass in an implementation of IFileProvider, then hosting on Android may be possible. There are certainly other web servers that do run on Android (in Java), but anyone who wants to build a Xamarin app will have a much harder time since Asp.Net Core Hosting doesn't start up correctly. Enterprising users may want to fork and modify this repo to implement a hypothetical `AndroidHostBuilder : IWebHostBuilder` to avoid FileSystemWatcher, but that's quite involved. Are there any other possible solutions?

**Comment by muratg** [comment]
cc @glennc @DamianEdwards

**Comment by DamianEdwards** [comment]
Would changing to the polling file watcher implementation help here? Today it's possible via an environment variable I believe.

**Comment by AdamDotNet** [comment]
I just wanted to add that taking the 2.1.1 tagged source code from this repository and hacking it horribly to avoid instantiating `FileSystemWatcher` in `HostingEnvironmentExtensions.Initialize` and `FileConfigurationExtensions.SetBasePath`, Asp.Net Core can start up and run middleware.

If mono/mono/issues/6966 is what I hope it is, namely adding the implementation of `FileSystemWatcher` to Mono's mobile profiles, then there's relatively good hope that Asp.Net Core can start up on Android without forking/modifying this repository's code.

**Comment by ggimenes** [comment]
Any workaround?
I tried to **remove the creation** of FileSystemWatcher in the  PhysicalFileProvider.cs, but i received many other erros on server initialization:

My code:

```
var host = Program.BuildWebHost(new string[] { });
host.Start();

public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseKestrel()
            .UseStartup<Startup>()
            .UseUrls("http://localhost:8989/")
            .Build();

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader().AllowCredentials());
            app.UseMvc();
        }

```


Android output log file is attached.
[log.txt](https://github.com/aspnet/Hosting/files/2215551/log.txt)

Some errors:

```
07-20 15:45:08.321 D/Mono    (28763): AOT: image 'System.ComponentModel.DataAnnotations.dll.so' not found: dlopen failed: library "/data/app/Nepos.Mobile.Cockpit-1/lib/arm/libaot-System.ComponentModel.DataAnnotations.dll.so" not found
Loaded assembly: System.ComponentModel.Annotations.dll [External]07-20 15:45:08.321 D/Mono    (28763): AOT: image '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/System.ComponentModel.DataAnnotations.dll.so' not found: dlopen failed: library "/data/app/Nepos.Mobile.Cockpit-1/lib/arm/libaot-System.ComponentModel.DataAnnotations.dll.so" not found

07-20 15:45:31.921 D/Mono    (28763): Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/gac/Microsoft.AspNetCore.Mvc.Abstractions.resources/2.1.1.0_pt_adb9793829ddae60/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'.
07-20 15:45:31.921 D/Mono    (28763): Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'.
07-20 15:45:31.921 D/Mono    (28763): Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/gac/Microsoft.AspNetCore.Mvc.Abstractions.resources/2.1.1.0_pt_adb9793829ddae60/Microsoft.AspNetCore.Mvc.Abstractions.resources.exe'.
07-20 15:45:31.921 D/Mono    (28763): Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/Microsoft.AspNetCore.Mvc.Abstractions.resources.exe'.
07-20 15:45:31.921 D/Mono    (28763): Assembly Loader probing location: 'pt/Microsoft.AspNetCore.Mvc.Abstractions.resources.dll'.
Exception:

System.IO.FileNotFoundException: 
```

**Comment by ggimenes** [comment]
It's working! =D
Despite the errors, the service was being executed, but the controller did not respond.
The problem was the version of the System.Threading.Tasks.Extensions package, which was in version 4.3.0 and should be in 4.5.0.
Now it's working normally!
Here's the nugget I'm using to overwrite the FileSystemWatcher used by Mono.
[Microsoft.Extensions.FileProviders.Physical.2.1.3-rtm-t000.zip](https://github.com/aspnet/Hosting/files/2220222/Microsoft.Extensions.FileProviders.Physical.2.1.3-rtm-t000.zip)

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
