### ISSUE TITLE
SelfHostDeployer still produces AddressInUseException

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Hosting#1296]
We run into [this](http://aspnetci/viewLog.html?buildId=366598&tab=buildResultsDiv&buildTypeId=Lite_MvcTest#testNameId7765957466554203500) kind of thing still. I believe previously @anurse added extra logging to this scenario.

**Comment by muratg** [comment]
@anurse what's the work proposed here?

**Comment by anurse** [comment]
Depends on if this is still a persistent problem on the CI. In order to figure out why it's still happening, we'd either need more logging or to make our tests way more defensive about addresses being in use.

**Comment by ryanbrandenburg** [comment]
It is [still](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=397530&_focus=108053) happening on the CI. When you say more logging you mean in the SelfHostDeployer right?

**Comment by anurse** [comment]
Yes

**Comment by muratg** [comment]
@JunTaoLuo Whenever you have some free time, can you take a look?

**Comment by ryanbrandenburg** [comment]
[Here's](http://aspnetci/httpAuth/app/rest/builds?locator=tag:PortFail,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) a non-exhaustive (but reasonably through) list of the builds that were failed by this. As you can see it happens about once or more per-day.

**Comment by ryanbrandenburg** [comment]
Any movement on this? It fails 2+ times a day.

**Comment by JunTaoLuo** [comment]
I'll make some time to take a look at it this week.

**Comment by mikeharder** [comment]
SelfHostDeployer currently works as follows:

1. Bind a socket to port `0`
1. Query the socket to determine the assigned port (say `56789`)
1. Dispose the socket
1. Start another process, and tell it to use the earlier assigned port `56789`
1. Other process binds to assigned port `56789`

This design was based on the assumption that the OS will not reuse the assigned port between step 3 and step 5.  This assumption is usually true, but sometimes the OS does reuse the port, which causes one of the external processes to fail to bind.  See repro at https://github.com/mikeharder/GetNextPort, which fails after a few seconds on my machine.

The most reliable workaround is to always start the external process on port `0`, then have the external process communicate back the assigned port.  SelfHostDeployer already has logic for this: 

https://github.com/aspnet/Hosting/blob/311a92ddee5a009b2e96beb18838e816b66d533b/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/SelfHostDeployer.cs#L135

But it also has logic to handle apps which **don't** print the assigned port.  It appears the only apps which don't print the assigned port are tests specifically for this logic:

https://github.com/search?utf8=%E2%9C%93&q=org%3Aaspnet+statusmessagesenabled&type=Code

So, I think the most reliable fix:

* Remove `GetNextPort()` and `StatusMessagesEnabled` from SelfHostDeployer
* Always start external processes on port 0, and require them to print the assigned port as a status message

SignalR also uses `GetNextPort()`:

https://github.com/aspnet/SignalR/blob/ff43390ed2ddd8ad9274fd2c99ae330fe31e743c/test/Common/ServerFixture.cs#L35

But I believe it can be changed to use port `0`.

Kestrel also uses `GetNextPort()` in AddressRegistrationTests:

https://github.com/aspnet/KestrelHttpServer/blob/4afaa386db527e1ff168389bb189ddbecd8deaff/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs#L998

This usage needs to stay, since it's specifically testing that Kestrel can bind to a non-zero port.  There's still a race condition if AddressRegistrationTests is running in parallel with another process binding to port 0, but even if this happens, the frequency of this failure will be significantly reduced (likely to 0).

Will send a PR tomorrow.

**Comment by Tratcher** [comment]
Keep in mind that HttpSys also uses the SelfHost deployer in ServerTests and MusicStore and doesn't support binding to port 0. I don't see it calling GetNextPort directly, but I don't recall how it's test port is allocated otherwise.

**Comment by ryanbrandenburg** [comment]
[This](http://aspnetci/viewLog.html?buildId=432346&buildTypeId=XPlat_Windows_Win8_Universe) particular presentation of this error is new to me.

**Comment by mikeharder** [comment]
@ryanbrandenburg: What is different about http://aspnetci/viewLog.html?buildId=432346&buildTypeId=XPlat_Windows_Win8_Universe?  It looks like the typical error message:

```
| [2018-03-27T05:08:07] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning:
dotnet stderr: Unhandled Exception: System.IO.IOException:
Failed to bind to address http://127.0.0.1:57896: address already in use. --->
Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted ---> 
System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by ryanbrandenburg** [comment]
What was different to me was that it was throwing CSC 255 at the top of the exception and was showing a stack-trace out of CompilerServices.

**Comment by muratg** [comment]
Updating the milestone as we're closing on preview2. If this is ready to checkin to release/2.1 branch, though, I think we should still be able to.

**Comment by muratg** [comment]
@mikeharder Do you plan to do any work on this in RC1?

**Comment by mikeharder** [comment]
@muratg: Yes, I will work on this tomorrow and Friday.
