### ISSUE TITLE
Urls not read from appsettings.json

### ISSUE THREAD

**Issue by b-stime** [aspnet/Hosting#1299]
See https://github.com/aspnet/Hosting/pull/1298 for my quick attempt at a fix via the GitHub web interface.

**Comment by b-stime** [comment]
@muratg
@Tratcher 

> What are you exactly trying to fix? Is there a bug filed for the issue you're targeting here?

> This code doesn't compile. _startup.Configure is a method, not an IConfiguration instance. I'm closing this and we can discuss it issue over at #1299.

I guess this may've already been discussed at some length\* but it continues to burn new users (e.g., me)...

The issue is that you don't appear to be able to configure the webhost port via a config file or command line out of the box when you create a project via:

$ dotnet new razor

The WebHostBuilder already parses appsettings.json and the command line args and hydrates the Startup object IConfigure so my patch attempt seemed like an easy way to reduce astonishment.

\*       https://stackoverflow.com/a/45854704/93345
          // https://github.com/aspnet/Hosting/issues/1148
            // https://github.com/aspnet/KestrelHttpServer/issues/1851

**Comment by Tratcher** [comment]
[Rambling investigation]

The command line issue was fixed here: https://github.com/aspnet/MetaPackages/issues/221. The workaround is here: https://github.com/aspnet/MetaPackages/issues/221#issuecomment-335207431

A similar workaround works for appsettings.json as well. 

The new Kestrel config file support also reads from appsettings.json.
https://github.com/aspnet/KestrelHttpServer/issues/1290#issuecomment-353416087

So the remaining gap is reading Urls from appsettings.json. Right now it's read from the wrong config layer. Hosting builds an initial configuration and services so it has enough information to build the rest of the app, like the Environment. But it also reads Urls from this config.
https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L290

The other config is built seperately and added to the app services: https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L246-L256

Option A to fix this would be to resolve the IConfiguration from the app services like how it resolves the server except as optional.
https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L284
That config could be used as another entry in the fallback search, likely after the existing items to minimize the compat risk.
https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L290


Or option B we change WebHostBuilder to pass in the app's config into WebHost from `_context.Configuration` rather than the host config, but this would affect more components and be a riskier change.
https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L257
https://github.com/aspnet/Hosting/blob/cd3f58bed7234ed5035a995c8688dccd6706b584/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L186-L190

Recommendation: Option A

**Comment by muratg** [comment]
We'll reconsider this in 2.2 

cc @glennc

**Comment by muratg** [comment]
Recommendation is to set the URLs with server specific settings. We won't be making other changes here.

**Comment by sharmilasubbiah** [comment]
Did this " Urls not read from appsettings.json or command line to Urls not read from appsettings.json" sorted ?? I am trying to make this work with no luck . Just wondering if you can help me please , thank you

**Comment by Tratcher** [comment]
No, we opted not to take this change. 2.1 offers a different way to configure urls for kestrel from the config file. See the new kestrel docs. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x#how-to-use-kestrel-in-aspnet-core-apps

**Comment by Tratcher** [comment]
The command line urls parameter did get fixed for 2.1.

**Comment by flaviofak** [comment]
It seems that the impact should be small because the host's config in used as the first config provider when creating the app's config. Why would option B be so risky?
Also, is it planned to be done in a future version? This behavior causes some problems when defining custom IServer classes, because each one should manually read the URLs configuration when you could have that information resolved for everyone.

**Comment by Tratcher** [comment]
The host's config and app's config are constructed differently, and _context.Configuration is completely replaceable so it may not be based on the host's config. Changing this risks regressing apps that are working today. You can already achieve the same functionality using Kestrel's new config section.

**Comment by devinvisible** [comment]
I wasted a lot of time on this, assuming that `{ "urls": "http://0.0.0.0:5050/" }` would take effect if it was in the `appsettings.json` file. Bummer. The aforementioned doc page was also misleading to me. The [Endpoint configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x#endpoint-configuration) section mentioned "`urls` host configuration key" which I assumed referred the key-balue pairs found in the `appsettings.json` file... but found I was wrong. Pretty frustrating.

The following `appsettings.json` configuration ended up working:
```
{
	"Kestrel": {
		"EndPoints": {
			"Http": {
				"Url": "http://0.0.0.0:5090/"
			}
		}
	}
}
```
