### ISSUE TITLE
Getting a SignalR HubConnection from TestServer

### ISSUE THREAD

**Issue by idubnori** [aspnet/Hosting#1336]
Is it possible? How does an integration level test using SignalR and TestServer on UnitTest?
I could not find out this example.

**Comment by Tratcher** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
Your question on [stackoverflow](https://stackoverflow.com/questions/49023582/initializing-hubconnection-from-testserver-in-asp-net-core-signalr) provides more info.

What does your `Startup` class look like? Did you setup SignalR and add a Hub Endpoint at "/fooHub"?

**Comment by idubnori** [comment]
@BrennanConroy 
> What does your Startup class look like? Did you setup SignalR and add a Hub Endpoint at "/fooHub"?

Of course, StartUp  has `services.AddSignalR();` and `app.UseSignalR(routes => { MapHub<FooHub>("/fooHub"); });` and there is a proper Hub. Actually my code-base is running on IISExpress / Self-Hosted. My concern is just TestServer within UnitTest.

**Comment by JimmyHannon** [comment]
I think it would be possible if there was an additional overloaded method of CreateHandler that accepts a route parameter. That route could be added to the pathBase of the created ClientHandler. Or something like that. Because right now, the handler returned by CreateHandler only has the basePath configured and if that handler is added on the SignalR hub using the WithMessageHandler the configured route for the hub is never used.

**Comment by Tratcher** [comment]
It should work fine if you don't set the path base, I don't see why any changes to CreateHandler are needed.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
