### ISSUE TITLE
Response caching component

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#137]
Assumption: MVC and other application level components will set standard HTTP cache headers (Cache-Control, Vary, etc.) for clients and proxies.

Also implement middleware and/or server support for reading the response headers and caching. It can then short circuit incoming requests and serve them from the cache.

**Comment by Tratcher** [comment]
@muratg Needs a new repo - ResponseCaching

**Comment by Tratcher** [comment]
New repo: https://github.com/aspnet/responsecaching

**Comment by Tratcher** [comment]
Related: Our IIS plugin and (soon) WebListener have limited access to the kernel mode cache. See https://github.com/aspnet/WebListener/issues/121

**Comment by darrelmiller** [comment]
The HttpMessageHandler based HttpCache I wrote here https://github.com/tavis-software/Tavis.PrivateCache/blob/master/src/PrivateCache/PrivateCacheHandler.cs has all the caching logic as per rfc7234.  Because I built it as a private cache there are a few conditions that shared caches need to account for that I didn't take into account.  I believe the full set of conditions are in the diagrams here http://bizcoder.com/caching-is-hard-draw-me-a-picture which I used as a basis for the code.
There is one scenario I am still working on which is when the vary header changes over time and there are multiple cached variants that had different vary headers when they were originally cached.  I expect my storage interfaces are going to change due to this, but your storage implementation requirements are going to be completely different than mine anyway.

Not sure if this is of any use to you, but just wanted to make sure you knew it was there.

**Comment by darrelmiller** [comment]
This may or may not be useful, but I recently updated my [HTTP caching library](https://github.com/tavis-software/Tavis.HttpCache) to handle variants properly and added the logic applicable to shared caches.   It uses the System.Net.HTTP  classes, but most of the logic should be the same.  The logic is based on the diagrams [here](http://bizcoder.com/caching-is-hard-draw-me-a-picture).

**Comment by davidfowl** [comment]
@Tratcher why is this in hosting and not on the https://github.com/aspnet/ResponseCaching repo

**Comment by Tratcher** [comment]
@davidfowl because the response caching repo is newer than this issue. It also needed design to figure out where the pieces belonged.  We can close this out now and create new items in ResponseCaching.

**Comment by Tratcher** [comment]
https://github.com/aspnet/ResponseCaching/issues/1
