### ISSUE TITLE
Application uses unfiltered Request-Id from any internet client

### ISSUE THREAD

**Issue by brendankowitz** [aspnet/Hosting#1385]
We recently encounted a situation where a third-party application which was using Application Insights, this application calls our API which is using .NET Core 2. The 3rd party app used multiple threads for multiple requests which resulted in these incoming requests having the same "Request-Id" in the header. This is not the problem, the problem is our API pulls out the Request-Id from the incoming request and uses it as the Root Id, I feel that this is not a desired behavior.

Another example, I could send in a Request-Id header of "JUNK", "SPAM", etc to an ASP.NET Core application and this would be used as the root operation Id in Application Insights.

There should be a setting/flag/config or something that can determine when an application is part of an internal call vs being exposed to the public internet.

This is where I can see the header is being consumed:
https://github.com/aspnet/Hosting/blob/release/2.1/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L57
This concrete class is then consumed here:
https://github.com/aspnet/Hosting/blob/release/2.1/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs#L37
etc.. 

Our current work around is to replace `HttpContextFactory` with a custom implementation that removes the header before it returns the HttpContext, this forces the app to create a new root Id as desired.

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
Huh, that's interesting. Maybe we should have a header filtering middleware.

**Comment by Tratcher** [comment]
This happens too early for middleware, it would have to be a feature of the server or context factory.

**Comment by davidfowl** [comment]
What exactly is the ask here? That this be opt-in?

**Comment by brendankowitz** [comment]
Yes I think it should be opt-in, safe by default

**Comment by cwe1ss** [comment]
The same happens for baggage ([Correlation-Context header](https://github.com/aspnet/Hosting/blob/55e57af8156eab2c28c62b5c6c5473405cb1c411/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L252)) of course. 

As soon as an application developer enables anything that subscribes to the relevant DiagionsticSource-Activities (e.g. Application Insights), .NET happily sends any IDs & baggage to ANY host without any filtering [via HttpClient](https://github.com/dotnet/corefx/blob/013a2ed3e6312dd2579a2d79f2e2324706fc4bc3/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L77) and ASP.NET Core happily receives anything.

There's also already issues regarding this in the Application Insights repositories - e.g. https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/536

All of this hard-coded propagation code should have never made it into .NET as it is insecure, non-configurable and proprietary (these header names [will NOT become a standard](https://github.com/w3c/distributed-tracing)). It might even violate privacy laws (imagine someone adds the username/email to the baggage for internal correlation and you happily send it to external hosts), 

Instead, this should always have been a part of the Application Insights SDK where they could have provided the necessary configuration options etc. 

I've raised my concerns about this per email when it was introduced to @karelz and @vancem but these issues have not been addressed since then. @blowdart maybe you have some leverage here to bring this back on the table.

**Comment by blowdart** [comment]
I'd argue this isn't insecure, it's acting as HTTP should - you accept headers from a client, and validation is left up to the components that user the headers. App Insights, for example, could have signed their headers, and rejected ones they know didn't come from them. It's not like .NET can know what headers other components are going to add, or depend on. If we look at the headers IIS Integration adds, it's IIS Integration that filters ones inbound that can cause problems.

**Comment by cwe1ss** [comment]
The insecure part I’ve meant here is HttpClient - it sends everything everywhere without giving people any chance to configure the behavior. You can’t even write a DelegatingHandler that removes headers because they are added right before the request is sent (DiagnosticsHandler).

One would have to setup a proxy that catches these outgoing requests to prevent baggage from leaving a system boundary.

IMO it was never necessary that this HAD TO be in the framework. Application insights could very well have written this propagation code in the DiagnosticSource subscribers.

**Comment by blowdart** [comment]
Oh I see. Insecure is debatable still IMO, but hell yes, the lack of configuration is a glaring problem :)

**Comment by cwe1ss** [comment]
The security risk is "information leakage" - but yes, it's not actively exploitable.

I'd like to add a few more things regarding your comment.

> @blowdart I'd argue this isn't insecure, it's acting as HTTP should - you accept headers from a client, ...

This part is fine. ASP.NET Core itself couldn't decide which headers to keep or drop (unless maybe there's some protocol violation) - it's responsible for making headers available to later components via the Headers collection. 

> @blowdart ...  and validation is left up to the components that user the headers. 

True, but the question is what's the 'component' in this case? I'd argue that it's `Activity` and the actual parsing code in [ASP.NET Core](https://github.com/aspnet/Hosting/blob/55e57af8156eab2c28c62b5c6c5473405cb1c411/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L246) & [System.Net.Http](https://github.com/dotnet/corefx/blob/5c521c8dd9e46c2da34ead4046000c3c3c4e998f/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L75). It's NOT Application Insights (or any other subscriber) as they are just consumers of this data and currently don't have a way to validate/change these fields (the baggage is currently append-only).

> @blowdart ... App Insights, for example, could have signed their headers, and rejected ones they know didn't come from them. 

See previous sentence. Application Insights doesn't access the headers anymore - it only reads the - already processed - data from `Activity`.

As you might now, `Activity` is based on [OpenTracing](http://opentracing.io)'s `Span` concept. However, there's no counterparts to OpenTracing's other concepts which leads to this problem. The concrete thing I'm criticizing here is the lack of OpenTracing's [Inject/Extract concepts](http://opentracing.io/documentation/pages/api/cross-process-tracing.html) which moves the responsibility of injecting/extracting headers to the tracer/subscriber. This frees the instrumentation from having to define header names and gives tracers the possibility to validate them and to offer hooks for application developers to enable/disable propagation for certain requests. 

Another (much less critical) side effect of this inability to configure the behavior is that .NET Core also sends the "Request-Id" even if the underlying DiagnosticSource subscribers don't even need it - e.g. in case of a monitoring system (e.g. prometheus) that subscribes to these events but doesn't need cross-application correlation.

**Comment by muratg** [comment]
@blowdart do you want anything done for 2.2?  If so, please file a bug with specific feature(s) and we can triage that. Sounds like a few different ideas are in this issue, but I don't see a coherent ask.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
