### ISSUE TITLE
appsettings does not get reloaded when using UseConfiguration extension method

### ISSUE THREAD

**Issue by BennieCopeland** [aspnet/Hosting#1430]
The `appsettings.json` file is never reloaded on change when using the `UseConfiguration` extension method.

``` csharp
public static IWebHost DoesntWork(string[] args)
{
    var config = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appSettings.json", optional: false, reloadOnChange: true)
        .Build();

    return new WebHostBuilder()
        .UseKestrel()
        .UseConfiguration(config)
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();
}
```

Using the `ConfigureAppConfiguration` extension method however does cause the `appsettings.json` file to be reloaded on change.

``` csharp
public static IWebHost Works(string[] args)
{
    return new WebHostBuilder()
        .UseKestrel()
        .ConfigureAppConfiguration((builder, config) =>
        {
            config.AddJsonFile("appSettings.json", optional: false, reloadOnChange: true);
        })
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();
}
```

I've created a sample project that uses a feature toggle to optionally print "Hello World" on the home page.
Example project: https://github.com/BennieCopeland/AppSettingBug

**Comment by Tratcher** [comment]
That's expected. UseConfiguration copies all of the keys:
https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L24-L32

It would be nice to change this behavior in 3.0.

**Comment by RehanSaeed** [comment]
It's still unclear to me when to use `UseConfiguration` and `ConfigureAppConfiguration` in relation to configuring Kestrel from `appsettings.json`:

```
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            new WebHostBuilder()
                .UseKestrel(
                    (builderContext, options) =>
                    {
                        options.Configure(builderContext.Configuration.GetSection(nameof(ApplicationOptions.Kestrel)));
                    })
                    ...
```

**Comment by Steveiwonder** [comment]
I've been trying to solve this issue as well as far as I can tell when using 
`.AddJsonFile("appSettings.json", optional: false, reloadOnChange: true)`
this won't rigger an "OnChange" event when configuration is changed during runtime due to a condition in `FileConfigurationProvider`

```csharp
public FileConfigurationProvider(FileConfigurationSource source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }
            Source = source;

            if (Source.ReloadOnChange && Source.FileProvider != null)
            {
                ChangeToken.OnChange(
                    () => Source.FileProvider.Watch(Source.Path),
                    () => {
                        Thread.Sleep(Source.ReloadDelay);
                        Load(reload: true);
                    });
            }
}
```

Take note of the  `if (Source.ReloadOnChange && Source.FileProvider != null)`
When calling `AddJsonFile` this sets he FileProvider to null so this condition is never true.
I've tried trawling the source to see if the FileProfile for JsonSource is configured elsewhere or I might be miss understanding it completely.

.....


Having said that while writing this comment and looking at the source i found
```csharp
namespace Microsoft.Extensions.Configuration.Json
{
    /// <summary>
    /// Represents a JSON file as an <see cref="IConfigurationSource"/>.
    /// </summary>
    public class JsonConfigurationSource : FileConfigurationSource
    {
        /// <summary>
        /// Builds the <see cref="JsonConfigurationProvider"/> for this source.
        /// </summary>
        /// <param name="builder">The <see cref="IConfigurationBuilder"/>.</param>
        /// <returns>A <see cref="JsonConfigurationProvider"/></returns>
        public override IConfigurationProvider Build(IConfigurationBuilder builder)
        {
            EnsureDefaults(builder);
            return new JsonConfigurationProvider(this);
        }
    }
}
```
Which calls `EnsureDefaults` which looks like this is where the `FileProvider` will be setup. Using `PhysicalFileProvider`

Still - I cannot get file changes to work successfully :(

**Comment by Tratcher** [comment]
That is not related to hosting or this issue. Please open a new issue against configuration.

**Comment by Tratcher** [comment]
There's not a good way to fix UseConfiguration since it's an extension method on IWebHostBuilder which only has GetSetting and UseSetting and we're trying to avoid breaking the interface. 

This isn't an issue going forward because generic host has ConfigureHostConfiguration with first class config support.
