### ISSUE TITLE
Make WebHostBuilder implement IHostBuilder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1437]
Today we have 2 hosts, the generic host and the web host. Ideally, it should be possible to build extensions that work on both without having to compile against the Microsoft.AspNetCore.Hosting directly. We can do this with generic trickery to make sure things stay fluent:

```C#
public static class MyGenericHostExtensionMethod
{
     public static TBuilder MyFancyMethod<TBuilder>(this TBuilder builder) TBuilder where IHostBuilder => builder;
}
```

/cc @Tratcher @glennc 

Maybe a 3.0 thing.

**Comment by Tratcher** [comment]
Aren't we aspiring to move everything to IHostBuilder in 3.0 anyways?

WebHostBuilder implementing IHostBuilder would cause some method ambiguity. E.g.
`IWebHostBuilder ConfigureAppConfiguration(Action<WebHostBuilderContext, IConfigurationBuilder> configureDelegate);` vs
`IHostBuilder ConfigureAppConfiguration(Action<HostBuilderContext, IConfigurationBuilder> configureDelegate);` with the different context and return types.

They could all be made explicit, but not sure what you'd gain.

**Comment by davidfowl** [comment]
> Aren't we aspiring to move everything to IHostBuilder in 3.0 anyways?

Yes aspiring, but WebHostBuilder won't be going anywhere in a hurry.

> They could all be made explicit, but not sure what you'd gain.

This issue literally explains what you'd gain. The ability to write extension methods that don't reference the WebHostBuilder directly while we transition people over. I'm not sure we're going to deprecate WebHostBuilder anyways, that's still TBD.

**Comment by edwardwilson** [comment]
This is exactly something I am looking for! Working in a large distributed company with hundreds of services all migrating to core it would be great to have standard ways of building processes (aspnet or console apps/services). 

Having many custom extension methods to congifure service collections, making sure all our systems are set up for logging and monitoring in standard ways have to be writen twice for different targets which is error prone!

Long term (sooner rather than later) a generic builder would be ideal. Configuring service collections, logging and process life cycle should be generic. 
``` csharp
 new HostBuilder()
        .ConfigureLogger( ... )
        .ConfigureServices( ... )
        ...
        .UseConsoleLifeTime()
        ...
```
Finally we could then have a way to register a process into the host (or more than one)!
```csharp
.AddProcess<MyWebProcess>()
.AddProcess<MyBackgroundProcess>()
```

Whrer the processes look similar to:
```csharp
public class MyWebProcess : WebProcess
{
 ....
}

public class MyBackgroundProcess : BackgroundProcess
{
...
}
```

**Comment by maelgrove** [comment]
@davidfowl 

I'm a little reserved about this because while it's certainly easy to make `WebHostBuilder` implement `IHostBuilder` and having a some more 'open' extension signature that works for both, there's the problem that their implementations don't work exactly the same way.

For instance, the `WebHostBuilder` creates it's own specific instance of `WebHost` and initializes it before returning, while the `HostBuilder` resolves the `IHost` from the container (causing certain differences in behavior as I described #1421), thus explicitly allowing the implementation to be swapped out. Another example would be the `IApplicationLifetime`: The `WebHostBuilder` _service locates_ it from the container during startup, while the `Host` gets it injected upon resolving in the constructor (and then still expects a certain implementation).

So depending on the facility, I need to be aware of the respective internal implementation because depending on the way services are injected or resolved, I might run into a cyclic dependendy conflict, or don't have my services being resolved at all. Let's say I want to write an extension that provides a different `IApplicationLifetime` with the purpose of shutting down the host as soon as it starts (makes sense, ikr): A `IApplicationLifetime` can have a `IWebHost` injected for the web hosting facility, but it can't for the generic hosting. To prevent that, I'd need to write specific extension methods for both, which kinda defeats the purpose of having an open extension contract.

**Comment by davidfowl** [comment]
You're never supposed to replace the IApplicationLifetime so I don't think you can use that as a reason for *not* doing this. Is there another example that doesn't involve intrinsic services provided by the host itself?

**Comment by davidfowl** [comment]
I think this doesn't make much sense anymore given the direction we're taking in 3.0 moving things to the generic host.
