### ISSUE TITLE
LoggerFactory.Dispose not called on app shutdown

### ISSUE THREAD

**Issue by bruno-garcia** [aspnet/Hosting#1466]
I have an implementation of `ILoggerProvider` which on `Dispose` executes some code. It seems `Dispose` is not called at all though.

I've created a [small repro](https://github.com/bruno-garcia/repro-logger-provider-dispose) where I add a provider which does a `Console.WriteLine` (and Out.Flush) on dispose, which never gets called. 

I tested it by running via `dotnet app.dll` and using CTRL+C (supposely a graceful shutdown).
It does print: `Application is shutting down...` but I don't see the print from the provider `Dispose`.

```shell
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c
```

**Comment by cwe1ss** [comment]
There's a few things problematic/wrong in your repro:

* You're adding two instances of your provider! One in `ConfigureServices` and one via `ILoggingBuilder.AddProvider(ILoggerProvider)` (which calls [services.AddSingleton(loggerProvider)](https://github.com/aspnet/Logging/blob/e9f9ad7379c3bf1707fa35bced6bdeadd409ba72/src/Microsoft.Extensions.Logging/LoggingBuilderExtensions.cs#L24) under the hood) 
* I think [your DI service registration call](https://github.com/bruno-garcia/repro-logger-provider-dispose/blob/5cd27792480af4b6b7d0b4f8c32b52f33cbcee26/TestLoggerProvider.cs#L27) isn't picked up by the logging framework, because you only register the actual type. The DI framework does not check the type for interfaces. If you want to add the provider via DI you have to use something like `services.AddSingleton<ILoggerProvider, TestLoggerProvider>()`
* You're passing your own instance to the calls. I don't think the DI framework will ever call `Dispose` on such objects (by creating the object yourself you're responsible for the lifecycle...).

I think you should only have to do this one call and everything should work fine: `services.AddSingleton<ILoggerProvider, TestLoggerProvider>()`

**Comment by bruno-garcia** [comment]
You're right that registering an instance means I'd own the lifetime. Once I register the type, Dispose gets called.

I did register twice on purpose, and then called `GetService` just to show that even then, `Dispose` wasn't called. I didn't intend to register with DI at all though.

My expectation was that such app:

```csharp
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseShutdownTimeout(TimeSpan.FromSeconds(10))
        .ConfigureLogging((context, builder) =>
        {
            builder.AddProvider(new TestLoggerProvider());
        })
        .Configure(a =>
        {
            a.Use(async (context, next) =>
            {
                var log = context.RequestServices.GetService<ILoggerFactory>()
                    .CreateLogger<TestLoggerProvider>();

                log.LogCritical("Handling some request...");

                await next();
            });
        })
        .Build();
```

.. would call dispose on the provider I added through `ConfigureLogging`, but it doesn't.
Now that I looked at what `AddProvider` does, I noticed it simply registers it with DI, in this case again with an instance. There's no overload of `AddProvider` that will take a generic type parameter and no arguments.

Though if instead of using `AddProvider`, I simply register the type:

```csharp
.ConfigureLogging((context, builder) =>
{
    builder.Services.AddSingleton<ILoggerProvider, TestLoggerProvider>();
})
```

It works properly! Thanks for your help.
