### ISSUE TITLE
Add ApplicationId to IHostingEnvironment

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#177]
* On IIS we ask IIS for the right value
* When self hosting with our default `k web` it is probably the path on disk

```csharp
    /// <summary>
    /// A string that uniquely identifies the application on a machine. 
    /// </summary>
    string ApplicationId { get; }
```

**Comment by glennc** [comment]
@harshgMSFT You need this for some of the work you are doing now right?

**Comment by Eilon** [comment]
Is this the same as https://github.com/aspnet/Hosting/issues/70 ?

**Comment by muratg** [comment]
See https://github.com/aspnet/Helios/issues/113

**Comment by GrabYourPitchforks** [comment]
Discussed offline with some people. We think the best course of action right now would be to expose this in DataProtection (since only it and MVC require it, and MVC depends on DataProtection) for now. If we can find a legitimate scenario for moving this lower in the dependency chain into DNX or Hosting, then we can do that in a future release. The new API in DataProtection.Interfaces is [here](https://github.com/aspnet/DataProtection/blob/82d92064c50c13f2737f96c6d76b45d68e9a9d05/src/Microsoft.AspNet.DataProtection.Interfaces/DataProtectionExtensions.cs#L97).

@glennc - feel free to resolve as appropriate.

**Comment by muratg** [comment]
Closing this one.
