### ISSUE TITLE
API Review: Hosting Engine

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#236]
```csharp
public void Main()
{
    var builder = new WebHostBuilder(_serviceProvider, _config);

    builder.UseServices((sc) =>
    {
        sc.AddSingleton<IMyCustomService>();
    });
    builder.UseEnvironment("Staging");
    builder.UseServer("Microsoft.AspNet.Server.WebListener");

    var host = builder.Build();

    var waitHandle = new ManualResetEventSlim();

    var shutdown = host.ApplicationServices.GetRequiredService<IApplicationShutdown>();
    shutdown.ShutdownRequested.Register(() =>
    {
        host.Dispose();
        waitHandle.Set();
    });

    host.Start();

    waitHandle.Wait();
}
```

* IHostingEngine moves to internal namespace
* New WebHostBuilder to build an engine, Use* methods from IHostingEngine move to it
* IServiceProvider is required for the builder. If you don't provide a configuration we use an InMemory one.
* Add UseUrl, UseUrls, UsePort methods to the builder. These set known keys on Configuration.
* UseServices method added to builder. Accepts the configureServices action.
* builder.Build needs to do the same thing that WebHost was doing in Create previously.

**Comment by HaoK** [comment]
@davidfowl Remind me why we didn't keep the iteration where we had Builder/Engine split like this before?  I know we had this split but decided to drop it...

**Comment by davidfowl** [comment]
That came up today and now I can't remember (that why we called you! :smile:). I might still exist somewhere in a PR.

**Comment by HaoK** [comment]
unfortunately I think this was in lync, does lync save history?

**Comment by davidfowl** [comment]
Only sometimes

**Comment by HaoK** [comment]
I think the difference in usage pattern here is configuring the service before calling start.  I don't think we considered that scenario when we killed the Builder/Engine split.  If we didn't expose ApplicationServices there isn't too much you could do with the engine after building it

**Comment by HaoK** [comment]
But I like this change, so I'm not trying to push back, just want to make sure there wasn't a real reason why we didn't do it before...

Can we add `UseStartup<TStartup>` for the builder?  I'm currently having issues getting this to work properly only in the TestServer, since we want TStartup to be activated from the builder's SP to work correctly

**Comment by davidfowl** [comment]
I think there is a UseStartup. The Builder has everything that the IHostingEngine had before that includes UseStartup

**Comment by HaoK** [comment]
@lodejard didn't want the Type one since I think it caused a bit of overload hell, but I think we can make it work via builder somehow.  I'll see if I can expose it in a limited way.  He didn't want it to bleed into the StartupLoader interface, which I think was his main concern.  As given a type, we don't have any way to get the startup methods out of a Type today.  Its an internal detail that the loader takes care of, so we'd have to split the interface into two methods instead of the single one today (which seemed like an ok trade off to me)
