### ISSUE TITLE
In-Process Selfhosting like Web API 2

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Hosting#291]
OWIN allowed you to selfhost the app in-process. This allowed you to selfhost Web API 2 in your desktop application.
```csharp
string baseAddress = "http://localhost:9000/";
using (WebApp.Start<Startup>(url: baseAddress))
{
    ....
}
```
As i've heard about ASP.NET 5 and MVC 6 finally being OWIN based i was very excited about having this chance with MVC too.
Since i couldn't find anything about it except
```json
"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
```
i tried fiddling with the hosting project. After hours of hacks going nowhere and reverse engineering some parts, copying from others, fighting nuget about dnx vs full clr and a shitload of code, i got it "somehow" running but MVC didn't feel like serving me any page and i only got 404 from the OWIN pipeline.
So far everything feels very rigid and dependent on many things, especially DNX, the existance of a damn project.json and a very specific directory structure, even if ASP.NET 5 is supposed to be losely coupled, flexible, running everywhere, etc. About running everywhere... i thought since ASP.NET is just a managed application and the raspberry pi seems to have a CLR, i could just copy over the managed assemblies and get it running.... nada, it doesn't really wants to without DNX which is dependant on native code but at least i've heard that you guys are working on the pi thing. Without DNX it's a pain in the ass and DNX is dependent on native code which doesn't makes me happy since i'm a purist but the latter thing is just by the way (but it makes me wonder, DNX feels like a third runtime beneath CoreCLR and CLR on which ASP.NET 5 applications ONLY wants to run).

So long after this rant my simple question is: how compatible are ASP.NET 5 apps and full CLR applications and will i be able to selfhost ASP.NET 5 applications in full CLR applications which are not designed to run on DNX.

**Comment by jakesays** [comment]
This could easily be solved by changing the product name to Asp.Node. If that were to happen then the behavior you're experiencing would be perfectly fine.

**Comment by davidfowl** [comment]
A few nits before I get to your main questions:

> OWIN allowed you to selfhost the app in-process. This allowed you to selfhost Web API 2 in your desktop application.

You mean Katana. Not OWIN.

> As i've heard about ASP.NET 5 and MVC 6 finally being OWIN based i was very excited about having this chance with MVC too.

ASP.NET 5 is not based on OWIN but supports OWIN. It's a nitpick but an important one. You can read about the evolution of Katana project and how it relates to ASP.NET 5 here http://blogs.msdn.com/b/webdev/archive/2014/11/14/katana-asp-net-5-and-bridging-the-gap.aspx.

> How compatible are ASP.NET 5 apps and full CLR applications 

Not very but that's intentional. The entire purpose of this new stack was to provide an abstraction that we can assume things without having to worry about what CLR was being used. In theory, implementing the `Microsoft.Framework.Runtime.Interfaces` is all you need to do to act like a "DNX" environment. That's the only connection between the APIs higher up the stack. We provide a default implementation based on any CLR the dnx itself runs on.

> will i be able to selfhost ASP.NET 5 applications in full CLR applications which are not designed to run on DNX.

We won't be providing a first class story for this because we don't the support burden. We built a new project system, new assembly loading engine and other things to avoid the currently messy policies that exist in the current .NET framework. Just imagine if we tried to run on the current vanilla .NET, people would expect full support, that means testing it in existing ASP.NET 4.x projects (and supporting it everywhere ASP.NET 4.x ran), they'll ask us to strong name the libraries so they can GAC it because some environments like Sharepoint require you to GAC components. 

ASP.NET 5 is new has been designed to run on the DNX. In the future we'll can make some libraries tied less tied to the dnx* target framework so that other people can provide hosts on other platforms (like .NET 4.5), but don't expect us to create, maintain and support one.

**Comment by davidfowl** [comment]
Related to https://github.com/aspnet/Hosting/issues/215

**Comment by Tratcher** [comment]
WebApp.Start is now WebHostBuilder.Start as shown here: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L37

**Comment by jakesays** [comment]
This is unsettling. You've basically created an entirely new product that is incompatible with 15 years of history. Good job.

I would love for someone to explain the rationale behind such thinking.

**Comment by davidfowl** [comment]
> This is unsettling. You've basically created an entirely new product that is incompatible with 15 years of history. Good job.

> I would love for someone to explain the rationale behind such thinking.

I already tried but maybe I failed.  Some things that might expand:

- http://docs.asp.net/en/latest/ 
- http://weblogs.asp.net/scottgu/introducing-asp-net-5
- http://channel9.msdn.com/Events/Build/2015/2-687

That said, .NET Framework isn't going anywhere, and you can still use it. This is a new world and people won't all move on day 1 but I expect the majority of green field applications to migrate because of the benefits of this new stack. Think of it like the move from ASP to ASP.NET.

**Comment by jakesays** [comment]
You're fracturing your own ecosystem, and yes, it is exactly like the move from ASP to ASP.NET, only this time you're really not improving things all that much. You say .net fw isn't going anywhere, but since the two systems are incompatible you're forcing people to choose. This will result in asp.net in .net to stagnate.

And your expectation of greenfield app development migrating is not realistic because to migrate we have to completely change the way we do web development. The value proposition of the new stack just isn't there to justify the costs.

We have decades of experience invested in the existing tooling, project system etc.

**Comment by Suchiman** [comment]
@davidfowl 
Okay can you elaborate on these abstractions?
What i mean is, which new problems have been raised that needs new abstractions?

Speaking in terms of abstractions and running things similiar, in case MS didn't notice, we had the CLR for Windows Desktop and Mono for linux.
Mono did an excellent job at providing a CLR like environment (except for the incomplete / not-always-bugfree BCL) on many platforms with a "compile once on AnyCPU and run everywhere" feeling and with the open sourcing of the BCL and the integration of it in Mono this was going to be way less a problem.

The compile once AnyCPU and the safety of .NET are some the most honored features .NET i believe which has also worked for some time now in mono and the CLR but with the raising fragmentation of the .NET platform and the coolness of removing features (e.g. AppDomains, msbuild, cutting off features from WPF and wondering why people are not excited about the new XAML platforms) and the increase of conditional compilation, this aspect is fading away, torwards something we know rather know from C/C++. About abstractions: when having dnxcore50 and dnx50, if i haven't lost track, the underlying CLR is apparently not abstracted or at least not the expectation wether the BCL is shipped or preinstalled.

So far noteable changes in DNX are the ability to run without compile and the built-in dependency injection, both features which don't need breaking changes but would have been possible with AppDomains and the latter is rather a design change in MS component design.
About setting virtual constraints... you can limit what people are expecting by clarifying the limits, you traded the question: "why are the assemblies not signed?" against the question: "why are dnx and .NET incompatible" which has a way bigger impact imho.

Customer: Why are .NET and DNX incompatible?
MS: We put virtual limits in place so you don't expect them to be compatible.
Customer: But why?
MS: Because we want to break with some older features.
Customer: Okay but why the virtual limits instead of documentation of limits?
MS: [Because customers are idiots and should be protected from themself](https://github.com/dotnet/corefx/issues/1420#issuecomment-96328476)
Customer: Wait what?
MS: Okay at least sometimes, but we don't honestly trust you to be able to handle great power.
Customer: ....

I don't know how often i've heard the term "empowering developers" but you rather try to put us in a sandbox so we can't get hurt while taking our toys which we could accidentally swallow.

**Comment by davidfowl** [comment]
@Suchiman @jakesays I'd rather not get into a debate like this on the Hosting github issue. If you're against the entire direction of the product, maybe start an issue on aspnet/Home. This is the direction we're currently going in, building a new platform for web developers using including things and also taking things into account like x-platform and being able to expose NuGet in a more first class way.

>The compile once AnyCPU and the safety of .NET are some the most honored features .NET i believe which has also worked for some time now in mono and the CLR but with the raising fragmentation of the .NET platform and the coolness of removing features (e.g. AppDomains, msbuild, cutting off features from WPF and wondering why people are not excited about the new XAML platforms) and the increase of conditional compilation, this aspect is fading away, torwards something we know rather know from C/C++. About abstractions: when having dnxcore50 and dnx50, if i haven't lost track, the underlying CLR is apparently not abstracted or at least not the expectation wether the BCL is shipped or preinstalled.

I hear you and the BCL team is fixing this. We're working on a story that will make .NET whole again but it'll be worse before it gets better. The fact that dnx45x and dnxcore50 exist are artifacts of how the system has worked up until now but I expect this to get better as we get closer to shipping.

On another note though, when you write a windows store application, you run within an app container, a custom CLR host that you never see. 

> So far noteable changes in DNX are the ability to run without compile and the built-in dependency injection, both features which don't need breaking changes but would have been possible with AppDomains and the latter is rather a design change in MS component design.

Everything expressed here is what we abstract and provide implementations for when running on the dnx https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.Runtime.Abstractions. 

> About setting virtual constraints... you can limit what people are expecting by clarifying the limits, you traded the question: "why are the assemblies not signed?" against the question: "why are dnx and .NET incompatible" which has a way bigger impact imho.

Assemblies aren't signed because it blocks scenarios we want to enable like easily swapping out packages and the source cod for said project. Strong naming makes binding redirects appear again, the dnx fixes that because we have a view of the entire dependency closure (defined in project.lock.json) and we can resolve the correct versions of components before your app is executed. 

As for this conversation:

> Customer: Why are .NET and DNX incompatible?
MS: We put virtual limits in place so you don't expect them to be compatible.
Customer: But why?
MS: Because we want to break with some older features.
Customer: Okay but why the virtual limits instead of documentation of limits?
MS: Because customers are idiots and should be protected from themself
Customer: Wait what?
MS: Okay at least sometimes, but we don't honestly trust you to be able to handle great power.
Customer: ....

I actually don't care about protecting users from themselves in this case. That's why I said we'd allow it to work if you implemented the interfaces that were required, there's nothing weird about that. Asking us to provide them out of the box is a different story, one we are not currently planning to do.

I'm closing this issue because it doesn't belong here anymore. Please reopen the bug on aspnet/Home.

**Comment by davidfowl** [comment]
@Suchiman you asked:

> Okay can you elaborate on these abstractions?

I'll show a few examples of things you'd need to implement on vanilla .NET 4.5 to make things work:

- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/DefaultAssemblyProvider.cs#L17:
-  `ILibraryManager` is used to discover dependencies of the application that reference MVC https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L49:
- `IApplicationEnvironment` is used to determine the application base path
- `IAssemblyLoadContextAccessor` is an abstraction over loading assemblies
- `ILibraryManager` is used in this case to get the list of compilation references from the application so that razor can compile views against them.

To be honest though the hardest one to implement would probably be the ILibraryManager (https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Abstractions/ILibraryManager.cs).

**Comment by davidfowl** [comment]
Also related https://github.com/aspnet/dnx/issues/1431

**Comment by Suchiman** [comment]
@davidfowl thanks... that will take me some time to get through, i respect your effort.

**Comment by davidfowl** [comment]
@jakesays 

> You're fracturing your own ecosystem, and yes, it is exactly like the move from ASP to ASP.NET, only this time you're really not improving things all that much. 

That's fair, but if we didn't think we were improving anything we wouldn't have done it to begin with. I hope that as more people use the new system, they appreciate the new scenarios it brings.

> You say .net fw isn't going anywhere, but since the two systems are incompatible you're forcing people to choose. 

Although you have to choose, they aren't totally incompatible so lots of sharing is still possible.

**Comment by LodewijkSioen** [comment]
I fully understand why a clean break was needed for dnx. However, as a maintainer of an organically grown 10+ year old application, it's kind of disappointing that at least mvc6 doesn't run on vanilla 4.5 unless we rewrite all WebForms, WCF, etc elements we have.

If I understand all this correctly, my project will be perpetually stuck on mvc5.

**Comment by davidfowl** [comment]
@LodewijkSioen not really why can't they just be mapped to different virtual directories on IIS? This isn't really an all or nothing. There are interesting ways to interop. We definitely won't support running MVC 6 or any of the current stack on `System.Web`. 

There are also other "creative" ways to make it work but none of them will be first class and supported. But as an example of what might be possible (this is totally untested BTW), you can theoretically use katana's System.Web host + the ASP.NET 5 OWIN adapter to host ASP.NET 5 in IIS side by side with the rest of your application. 

There's tons of lego pieces, you just have to know how to put them together :smile:

**Comment by LodewijkSioen** [comment]
Given enough Duct Tape... :weary:

Two virtual directories seems like a lot of overhead for installation/updating (we're installed on-premise). Also that means another project, which means juggling the shared resources around. Your 'creative' solution seems more appealing. I'll try to throw some code at this to see what the possibilities are.

**Comment by davidfowl** [comment]
Sure but this is a something we are specifically not targeting. System.Web doesn't go with this new stack and we don't plan to run on it.

**Comment by jakesays** [comment]
So basically what you're saying is "Oh yeah you can use your existing code, but only if you hack the hell out of it" - that is really a shit policy. If I want Legos, I'll go to walmart.

"We definitely won't support running MVC 6 or any of the current stack on System.Web." - David I'm not sure if it's just your style or you really are an offensive ass, but what we get from you is "I really don't give a shit about your past investments in time and talent, nor do I care about your future. If you want to continue to innovate with us, you'll do it our way. If not, then fuck off."

Forgive my tone, but as a long time member of the .net community this really sucks.

**Comment by darrelmiller** [comment]
@jakesays System.Web carried many years of legacy that is very difficult to fix without making a clean break.  However, I can assure you that the decision was not taken lightly.  There were long debates and much consultation with the web community on the subject.  
As painful as it is currently, the decision to drop system.web will definitely be worth it in the long run.

**Comment by LodewijkSioen** [comment]
@darrelmiller I've thought a bit about what you said there. It's not about dropping System.Web. Microsoft can drop that reference, no big deal. NancyFx, for example, doesn't need System.Web either. What I'm worried about is that I will never be able to upgrade to Mvc6 or SignalR3 because there is a large WebForms presence in my app that I can't just rewrite.

**Comment by davidfowl** [comment]
You'll be happy to know we enabled this scenario recently. It's not our mainline though but it should still work. Our packages now target a more liberal set of frameworks including .NET 4.5.1:

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.PlatformAbstractions;

namespace ConsoleApplication10
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.Run(context =>
            {
                return context.Response.WriteAsync("Hello World");
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var app = new WebHostBuilder()
                .UseServices(ConfigureServices)
                .UseServer("Microsoft.AspNet.Server.WebListener")
                .Build();

            using (app.Start())
            {
                app.ApplicationServices.GetRequiredService<IApplicationLifetime>().ApplicationStopping.WaitHandle.WaitOne();
            }
        }

        private static void ConfigureServices(IServiceCollection services)
        {
            services.AddInstance<IApplicationEnvironment>(new ApplicationEnvironment());
        }
    }
}

```

It's not perfect as some services that come from the DNX need to be provided but it's doable in most cases.

**Comment by LodewijkSioen** [comment]
So in theory, with some effort, it will be possible to have say, webforms and mvc6 (as a dnx app) in the same solution. Correct?

**Comment by davidfowl** [comment]
Not sure I'd that far but maybe? We're not supporting running asp.net 5 within system.web (there are a bunch of issues with that). But if you make it work then great but you're kinda "on your own" in terms of "official support"

**Comment by Suchiman** [comment]
@davidfowl that is great news! exactly what i had in mind, thank you :smile:
Testing it though was rather hard :neutral_face:, **nightly** package of hosting on myget was two weeks old so i had to build from universe... which failed first on non public repositories, then built most of it with strange non fatal errors and finally failed due to datetime locale parsing issues... but it built enough packages to try your sample code.
ApplicationEnvironment needs to be implemented on my side as i've figured out and installing the MVC package from the universe build failed due to `Failed to add reference to 'System.IO'. Please make sure that it is in the Global Assembly Cache.` so it was quite cumbersome which seems to be attached to everything ASP.NET 5 :weary: but at least it seems getting better :sweat_smile:

**Comment by davidfowl** [comment]
The build is all messed up right now. But give it should be good by tomorrow

**Comment by davidfowl** [comment]
@Suchiman we also have more more nuget feeds, you can try cidev(look at our nuget.config files)

**Comment by MJGraf** [comment]
Maybe I understood something wrong, but I just tried to add the Microsoft.AspNet.Hosting package to a csproj targeting .net 4.5.1. I used this feed: https://www.myget.org/F/aspnetcidev/api/v3/index.json and selected version Microsoft.AspNet.Hosting.1.0.0-rc2-16093.
It first installs a lot of packages successfully, but then fails with:
...
Adding package 'System.Text.Encodings.Web.4.0.0-rc2-23611' to folder 'C:\_Programmierung\MP2\MediaPortal-2\MediaPortal\Packages'
Added package 'System.Text.Encodings.Web.4.0.0-rc2-23611' to folder 'C:\_Programmierung\MP2\MediaPortal-2\MediaPortal\Packages'
Added package 'System.Text.Encodings.Web.4.0.0-rc2-23611' to 'packages.config'
Successfully installed 'System.Text.Encodings.Web 4.0.0-rc2-23611' to AspNetServer
Adding package 'Microsoft.AspNet.Http.Abstractions.1.0.0-rc2-16055' to folder 'C:\_Programmierung\MP2\MediaPortal-2\MediaPortal\Packages'
Added package 'Microsoft.AspNet.Http.Abstractions.1.0.0-rc2-16055' to folder 'C:\_Programmierung\MP2\MediaPortal-2\MediaPortal\Packages'
Install failed. Rolling back...
Package 'Microsoft.AspNet.Http.Abstractions.1.0.0-rc2-16055 : Microsoft.AspNet.Http.Features [1.0.0-rc2-16055, ), System.Text.Encodings.Web [4.0.0-rc2-23611, )' does not exist in project 'AspNetServer'
Is this supposed to work or did I understand this wrong?

**Comment by roji** [comment]
@davidfowl, a clarification on your [above code sample](https://github.com/aspnet/Hosting/issues/291#issuecomment-150558413): when you say .NET 4.5.1 can be used do you mean non-DNX .NET Framework? Because `ApplicationEnvironment` (used in the sample) is defined in Microsoft.Dnx.Runtime which doesn't target .NET Framework...

Am I right in understand that it's not possible to use WebHostBuilder in non-DNX .NET Framework?

**Comment by aL3891** [comment]
@roji There isn't really a dnx/non-dnx .net framework though.
Basically, there are two runtimes now, .net 4.6 and below (the full framework) and .net core (the new smaller one)

Asp.net 5 apps can target either of these two. Dnx is (or was rather, more on that in a sec) just the way to start the app and boot the runtime you wanted to use, so you'd tell dnx, run this app using .net46/.netcore/mono.

If an app targets .net 4.6 it can reference any "full framework" assembly, including anything in the bcl, such as System.Drawing or System.Web. So when the team says "you cant use system.web" they are really saying, you cant host an asp.net 5 app via the mechanisms in system.web (including the routing, meaning webforms postbacks wont work), not that you cant add a reference to system.web and use things in there (as long as you only target the full framework, not .net core in your project.json)

Now regarding dnx, alot of that is changing in RC2, dnx will be replaced by a new command line infrastructure that you can find i the https://github.com/dotnet/cli repo. Alot of stuff is still in motion here but as far as i understand, the concept of commands from dnx is going await and will be replaced by application code inside a good old static void main() in each application.  
Applications can still be run without compiling (dotnet run) but they can also be compiled to a regular exe file. 

Another thing that is coming in RC2 (probably) is a new way of specifying what a library targets. instead of specifying the runtimes as we do today (dnx46,dnxcore,mono,winrt and so on) libraries will specify what "platform standard" they support, and then that library will work on all the actual runtimes that support that standard. see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md for more info, its pretty cool.

One interpretation of your original question is, "can i run asp.net in an app that is using the csproj project system". And to that, the awnser is no. However you dont really need to since you can target both the full framework and .net core with the new project system. You can also reference assemblies compiled with the old proejct system in the new one (direct project references are also in the works, it might work now even)

@davidfowl please correct me if i've gotten anything wrong :)

**Comment by aL3891** [comment]
Also a note on partially moving from asp.net 4.6 and asp.net 5, since iis basically just deals with httpmodules that take turns processing the request, there is nothing stopping you from using both the platformhandler invoking asp.net and the old asp.net 4.6 handler in the same app.

That way, you can write parts of your app with the new stuff, and still have old web forms app around without really changing the original app, apart from the web config.

**Comment by Suchiman** [comment]
Just as a note here, i managed it to make MVC 6 work in a .NET 4.5.1 Console Application, roughly the way https://github.com/aspnet/Hosting/issues/291#issuecomment-150558413 describes first on cidev, then after a few days and adjusting some code again on the regular feed. Then i had updated it again aaaand it broke again. It was seemingly wildly changing what i need to come up with for and what's provided in the box and how to initialize the expected invariants so :sweat_smile: i couldn't keep up and i'm waiting for it to stabilize.

Between my fights with nuget and csproj, i got even greater confusion about which .NET Framework version the nuget dependencies require (they seem to be fixed on .NET 4.5.1, they don't allow 4.5.2 nor 4.5 though some other packages are targeted 4.5).

With the latest changes i'm wondering if the way ASP.NET 5 is initialized on dotnet vs. the selfhosting scenario is (nearly) identical, looking at https://github.com/aspnet/Templates/blob/34f58c97d6b4a4cc1beff6a573f1978d2a1ca2c8/src/BaseTemplates/EmptyWeb/Startup.cs#L34-L37

**Comment by roji** [comment]
@aL3891 thanks for that very clarifying comment, especially the big changes for rc2 - I was totally unaware of the new dotnet CLI and the ability to produce a simple EXE (that's a really welcome change).

And yes, my question was partially "can I run ASP.NET in a csproj project" - and I actually managed to do that via some pretty bad hacks. I'm aware that I can dump csproj for project.json and have done so in a few cases - it's definitely great. But the fact is that it's a pretty big transition for some projects, and not all tooling support project.json yet (e.g. R# unit test runner) - so in some cases people are still constrained to stay with csproj. If I understood your comment correctly, RC2 will make it so that I'm not longer required to switch to project.json in order to use ASP.NET 5, and so this problem goes away.

Thanks again!

**Comment by davidfowl** [comment]
@aL3891 great explanation. There are some issues with NuGet that make it difficult and sometimes impossible to use some the packages we produce in csproj based (packages.config) projects. `project.json` has 2 "gears", you can use it with a csproj for nuget references (this is what UWP projects do today), you can see an example here  https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/PackageManagement.UI. This will be expanded to more project types eventually. The other gear is xproj, which is the project.json based projects that we use now and will become .NET CLI projects as well. 

We're also working on a clean story for msbuild integration (the one we have today sucks) so you'll be able to reference csproj -> xproj and xproj -> csproj seamlessly (when in that msbuild world).

**Comment by roji** [comment]
@davidfowl that is really great news, interoperating with csproj has been a pain point. It's also great to be able to produce simple classical CLI projects (no DNX host, no dependency injection) with xproj/project.json/dnxcore50. Really looking forward to it.

**Comment by davidfowl** [comment]
Samples that we have so far here: https://github.com/davidfowl/dotnetcli-aspnet5

**Comment by aelij** [comment]
I've managed to host an ASP.NET 5 app in a .csproj without DNX by using some (naïve) implementations of IRuntimeEnvironment, IApplicationEnvironment and ILibraryManager.

https://gist.github.com/aelij/23293c61dcb59597f93c

@davidfowl There are still some errors when adding the MVC NuGet package (or rather some of its dependencies). I've had to manually add a reference to System.{IO,Runtime,Collections,Text.Encoding,Threading.Tasks} (by adding <Reference/> items to the .csproj), even though these are not .NET 4.5.1 assemblies.
