### ISSUE TITLE
Add an "X-Powered-By" and "X-AspNet-Version" header

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Hosting#327]
From aspnet/KestrelHttpServer#138

**Comment by benaadams** [comment]
Following up from @Daniel15 comment
> Is it worth adding something like X-Powered-By too? The server header is usually overwritten by reverse proxies (eg. Nginx).

Looks that that's a bug in the proxy? [rfc2616 14.38 Server](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

> If the response is being forwarded through a proxy, the proxy application MUST NOT modify the Server response-header. Instead, it SHOULD include a Via field (as described in section 14.45).

**Comment by benaadams** [comment]
Also:
>Note: Revealing the specific software version of the server might
      allow the server machine to become more vulnerable to attacks
      against software that is known to contain security holes. Server
      implementors are encouraged to make this field a configurable
      option.

**Comment by Daniel15** [comment]
> Looks that that's a bug in the proxy?

The section you quoted is for "regular"/forward proxies. RFC2616 says:
> The Server response-header field contains information about the **software used by the origin server** to handle the request. 

With a reverse proxy, the proxy itself is considered the origin server. See http://trac.nginx.org/nginx/ticket/538.

**Comment by benaadams** [comment]
RFC2616 does give conditions for a gateway in 14.45 Via
>The Via general-header field MUST be used by gateways and proxies to indicate the intermediate protocols and recipients between the user agent and the server on requests, and between the origin server and the client on responses. 

The fact the nginx bug tracker they consider themselves to be the origin server and quote mod_proxy to justify this is a bit of a reach since that continues to say:

> A typical usage of a reverse proxy is to provide Internet users access to a server that is behind a firewall. Reverse proxies can also be used to balance load among several back-end servers, or to provide caching for a slower back-end server. In addition, reverse proxies can be used simply to bring several servers into the same URL space.

The reverse-proxy acts as the origin for networking purposes meaning no client configuration is required. 

Following nginx argument though; it would mean all load balancers should overwrite the server header and all caches should overwrite the server header.

Examples of other reverse-proxies:

* **Varnish cache** 
 * Adds: *Via:1.1 varnish*
 * Example: https://www.varnish-cache.org/ or https://en.wikipedia.org/ or all of github.io
* **Apache Traffic Server** 
 * Adds: *via: http/1.1 usproxy1.fp.bf1.yahoo.com (ApacheTrafficServer)*
 * Example: https://www.yahoo.com/ 
* **Application Request Routing** 
 * Doesn't add anything; though sets a ARRAffinity cookie
 * Example: http://azure.microsoft.com/en-us/
* **Squid cache**
 * Doesn't add anything
 * Example: http://www.squid-cache.org/
* **AWS Cloudfront CDN**
 * Adds: *Via:1.1 d84fed7fd1b1bbf46db79b86f6968b79.cloudfront.net (CloudFront)*
 * Example: https://a0.awsstatic.com/main/css/1.0.170/style.css (on http://aws.amazon.com/ )
* **Google HTTP/HTTPS Load Balancing**
 * Adds: *Via: 1.1 google*
 * Example: ? docs here: https://cloud.google.com/compute/docs/load-balancing/http/

I think you comparison to gateway is accurate and nginx is poorly behaved.

**Comment by benaadams** [comment]
Updated nginx ticket: https://trac.nginx.org/nginx/ticket/538#comment:4

**Comment by darrelmiller** [comment]
It is worth noting that [RFC 7231](http://tools.ietf.org/html/rfc7231#section-7.4.2) has removed the language about proxies not being allowed to modify the server.  I not yet found the specific reasons why it was removed.  Still looking.

I personally don't think the intent of saying that a reverse-proxy looks like the origin web server to the client was intended to allow it to mask the existence of all infrastructure behind it.  The whole point of the layered architecture and the uniform interface is that each layer looks like the origin server.  I suspect the use of the word proxy in the 2616 text was intended to mean "intermediary".

**Comment by darrelmiller** [comment]
RFC 7230 states:

> An HTTP-to-HTTP gateway  MUST send an appropriate Via header field in each inbound request
> message and MAY send a Via header field in forwarded response messages.

> A "gateway" (a.k.a. "reverse proxy")

Based on this I would argue that it is valid for a gateway to add its identifier to the Via header of a response and therefore leave the server header untouched.  It is also valid for the gateway to change the server header and not add a via header.  As was mentioned earlier, this should be configurable.

Personally I would like to avoid having the X-Powered-By and X-ASPNET-Version headers appear in my responses.

**Comment by benaadams** [comment]
Interesting; have updated the ngnix ticket

**Comment by GuardRex** [comment]
> Personally I would like to avoid having the X-Powered-By and X-ASPNET-Version headers appear in my responses.

:+1: Please provide control to deactivate if it this request is approved. I think we should have that for `Server`, too. Otherwise, you have to [go to this trouble](https://github.com/aspnet/Home/issues/837#issuecomment-132401273):
```
public void Configure(IApplicationBuilder app) {
    app.Use(next => 
    {
        return ctx => 
        {
            ctx.Response.Headers.Remove("Server");
            return next(ctx);
        };
    });
    app.UseMvc();
}
```

**Comment by Eilon** [comment]
Whatever we do for this definitely must be turn-off-able. In previous versions of ASP.NET there was always a switch for this.
