### ISSUE TITLE
WebApplicationBuilder.ConfigureServices should be Func<IServiceCollection, IServiceProvider>

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#529]
It's currently `Action<IServiceCollection>` and goes on to use `BuildServiceProvider` to construct a service collection.

Slightly related - we could move `ServiceCollection` to DI.Abstractions so you don't have to import `Microsoft.Extensions.DependencyInjection` to instantiate the type.

**Comment by Tratcher** [comment]
:-1: `Action<IServiceCollection>` is far more common. `Func<IServiceCollection, IServiceProvider>` is for a specialized scenario. We can't have both because that causes resolution conflicts. We could have one with a different name like `SetServiceProvider(Func<IServiceCollection, IServiceProvider>)`.

**Comment by pranavkm** [comment]
> Func<IServiceCollection, IServiceProvider> is for a specialized scenario

Huh? It's the only way you can plug in a DI system into the application.

**Comment by Tratcher** [comment]
Yes, specialized

**Comment by davidfowl** [comment]
There's really 2 sets of ConfigureServices method and with the latest API rev, we cut one of them. There's UseStartup<T> where you can override Configure and ConfigureServices like normal and there's ConfigureServices which lets you configure hosting services, it does *NOT* map to configure services in the startup method (though that might be confusing). The latter we chose to expose because we didn't see the value in the host being able to override application services in Startup.

**Comment by pranavkm** [comment]
Should it be renamed to `ConfigureHostingServices`? The current name doesn't help in distinguishing between the two.

**Comment by davidfowl** [comment]
@pranavkm It's bit weird to override the app's `ConfigureServices` and `Configure` separately. It would need to be a UseStartup overload:

```C#
var application = new WebApplicationBuilder()
        .UseStartup(services =>
         {
               services.AddMvc();

               // Use autofac
               var containerBuilder = new ContainerBuilder();
               containerBuilder.Populate(services);
               return containerBuilder.Build().Resolve<IServiceProvider>();
         },
         app => 
         { 
              app.UseMvc();
         })
         .Build();
```

**Comment by pranavkm** [comment]
If you've seen how we use this in Mvc, we want the goodness of Startup discovery (via `UseStartup`) but need to setup enough things for the TestHost to execute it (via `ConfigureServices`).

**Comment by davidfowl** [comment]
Then why do you care about being able to specify the service provider? Where is the use case?

**Comment by pranavkm** [comment]
I'm not arguing for that now. Just renaming it so that it's easier to distinguish.

**Comment by davidfowl** [comment]
Hmmmm I dunno if I'd want to rename. I understand it's confusing though...

**Comment by glennc** [comment]
I don't think we are actually going to do this. If someone disagrees they can reopen this.

**Comment by joplaal** [comment]
I deeply disagree. We use StructureMap in other parts of the Core, and dependencies get configured through it. In the  Startup class we are able to return  `return container.GetInstance<IServiceProvider>();` at the ConfigureServices method. But when trying to use this scenario in our TestServer, it's now imposible, as far as I know. It was perfectly possible at rc1. Is any way we can configure the TestServer as we do in the real app? I think it has to provide the same options.

**Comment by joplaal** [comment]
I can not see at this point how to configure your custom ServiceProvider other than using the Startup class. I think that the startup way should be a easy to way configure the app, but the builder methods should provide the whole functionality. I would better understand that the startup class method would not return the service since one could argue that is not a common scenario, and the startup class method would be used in the most common scenarios. But the methods on the builder should not be limited. Which is the point to have a pluggable ServiceProvider if you can not configure it?

**Comment by TrabacchinLuigi** [comment]
there is no way i can use @davidfowl UseStartup overload that accepts two lambdas right ? that was just a proposal ?
I have no particular reason for wanting that, except i really like the compiler to know what i'm doing and complain when i'm doing it wrong, and the convention class does not, an this is something i really don't like

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
