### ISSUE TITLE
Clarification on intention with .UseEnvironment( ... )

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Hosting#537]
https://github.com/aspnet/Hosting/blob/dev/samples/SampleStartups/StartupFullControl.cs

:+1: This is **wonderful!**

Just a quick clarification on your intention though with the environment variable itself for `Hosting:Environment` ...

`.UseEnvironment( ... )` sets the environment, and I can see that when I check with DI on `IHostingEnvironment` and `.EnvironmentName`; however, it doesn't seem to actually set the environment variable value [when I explicitly check `Environment.GetEnvironmentVariable("Hosting:Environment")`].

Is this behavior "by design," or shouldn't the env var value change when `.UseEnvironment( ... )` is set explicitly?

**Comment by Tratcher** [comment]
By design. Hosting can read configuration from environment variables (and hosting.json and command line) but it never sets any. The UseXXX APIs are overriding the configuration, not modifying it.

Note the name of the environment variable associated with your deployment environment changed a while back from `Hosting:Environment` to ASPNET_ENVIRONMENT. On the command line and in hosting.json this and other hosting config can be specified without the ASPNET_ prefix.

**Comment by GuardRex** [comment]
@Tratcher ... ok ... and can I assume that for all intent and purposes thereafter, when I set it manually with `.UseEnvironment( ... )`, it will get picked up everywhere and used? Earlier, you and I (or @davidfowl and I) were discussing the inability to set the environment early enough in code to get it picked up everywhere. If this works out, I'm golden.

**Comment by davidfowl** [comment]
@GuardRex This already works.

**Comment by GuardRex** [comment]
Perfect. I'm all set and lov'in the new Hosting bits.
