### ISSUE TITLE
Microsoft.AspNet.TestHost.TestServer application base path mismatch

### ISSUE THREAD

**Issue by YahavGB** [aspnet/Hosting#666]
Hey guys,

I'm in the middle of adding a unit-tests for my ASP.NET Core application, and I'm struggling with some difficulty using the TestServer.

My project is based on an N-Tier architecture, so I got Project.Core, Project.Infrastructure etc. Likewise, my ASP.NET is located at Project.Web.UI and my unit tests is under Project.UnitTests.

My Startup.cs class used to read some files, such as configurations (appsettings.json) and certificate (for IdentityServer). For instance:

```

var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")

```

Now, when I'm trying to create a new server, using:

```
var server = new TestServer()
                  .UseStartup<Project.Web.UI.Startup>();
```

I'm getting an exception states that the appsettings.json file is missing, since the base path the TestServer is looking for is C:...\Project\Project.UnitTests instead of C:...\Project\Project.Web.UI .

I did manage to bypass this exception, by setting a custom environment name to the test server (e.g. "UnitTests") and then loading the file based on its value:

```
if (env.EnvironmentName == "UnitTests")
{
    var builder = new ConfigurationBuilder()
                    .AddJsonFile(Path.Combine(env.ApplicationRootPath, "../Project.Web.UI", "appsettings.json"));
}
else
{
    var builder = new ConfigurationBuilder()
                    .AddJsonFile("appsettings.json");
}
```

However this  approach should be app-wide and be implemented in each case, so I don't think that this is the way to go.

Is there any option to define the application base path in TestServer?

**Comment by dmccaffery** [comment]
@YahavGB This is normal behavior and was true with Owin self-hosting used for testing in the past when settings existed in an application configuration. Usually one would have a different configuration for test servers executing as part of an integration test (such as running on different port or using a different db) so that you can write tests that are non-destructive to real-world infrastructure.

As an example, I execute integration tests as part of deployment -- and I run destructive integration tests (tests that create or delete data) against a test db.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
