### ISSUE TITLE
Need a way to uniquely identify an application. 

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Hosting#70]
This is needed for 
https://github.com/aspnet/Mvc/issues/584

**Comment by harshgMSFT** [comment]
@yishaigalatzer @Eilon will we be  taking this for Beta3?

**Comment by Eilon** [comment]
@muratg - this is in his realm now.

**Comment by harshgMSFT** [comment]
@muratg any updates ... dont think we are getting this done for beta3?

**Comment by muratg** [comment]
@harshgMSFT we need to be closing on beta3 very soon there'a a couple higher pri items for @GrabYourPitchforks.   Also not sure if we should rush the design.  

@GrabYourPitchforks what do you think?

**Comment by yishaigalatzer** [comment]
@muratg @GrabYourPitchforks ping

**Comment by harshgMSFT** [comment]
@muratg ping. We need to converge on this. Lets meet this week and figure out our options.

**Comment by glennc** [comment]
Adding this to the agenda for next mondays core design meeting, unless you discuss it before then.

**Comment by harshgMSFT** [comment]
@glennc did we get any headway on this ?

**Comment by harshgMSFT** [comment]
@glennc , @muratg I do not see any updates for this since I pinged. Can one of you please update the status?

**Comment by muratg** [comment]
@harshgMSFT Looks like #177 is describing a way to do this in a specific way, and is assigned to you. Is this one OK to close?

**Comment by harshgMSFT** [comment]
Sure..lets keep the details in both bugs though.

**Comment by muratg** [comment]
@harshgMSFT See this bug filed by @GrabYourPitchforks: https://github.com/aspnet/Helios/issues/113

**Comment by GrabYourPitchforks** [comment]
Discussed offline with some people. We think the best course of action right now would be to expose this in DataProtection (since only it and MVC require it, and MVC depends on DataProtection) for now. If we can find a legitimate scenario for moving this lower in the dependency chain into DNX or Hosting, then we can do that in a future release. The new API in DataProtection.Interfaces is [here](https://github.com/aspnet/DataProtection/blob/82d92064c50c13f2737f96c6d76b45d68e9a9d05/src/Microsoft.AspNet.DataProtection.Interfaces/DataProtectionExtensions.cs#L97).

@harshgMSFT - feel free to resolve as appropriate.

**Comment by muratg** [comment]
@harshgMSFT Can we close this now?

**Comment by harshgMSFT** [comment]
Closing as we decided to use data protections api.
