### ISSUE TITLE
Startup fails when static method is passed to WebHostBuilder.Configure

### ISSUE THREAD

**Issue by nil4** [aspnet/Hosting#712]
```csharp
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;

static class Program {
    static void Main(string[] args) => new WebHostBuilder()
        .UseKestrel()
        .Configure(ConfigureApplication)
        .Build().Run();

    static void ConfigureApplication(IApplicationBuilder app) {}
}
```

Expected: the application starts up and `ConfigureApplication` is called.

Actual: the application crashes on startup with stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.ResolveApplicationName()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Program.Main(String[] args) in D:\projects\Repro\Program.cs:line 6
```

In [`WebHostBuilder.ResolveApplicationName`](https://github.com/aspnet/Hosting/blob/4e5fd908fd5eb33f55cf90f852f3328468e64e2a/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L257), `_startup.ConfigureDelegate.Target` is assumed to be non-null. This assumption is invalid for static methods.

**Comment by nil4** [comment]
Pull request #713 resolves this issue by using `_startup.ConfigureDelegate.GetMethodInfo().DeclaringType` instead.

**Comment by khellang** [comment]
Doesn't #714 get rind of this code completely?

**Comment by davidfowl** [comment]
Nope, we still determine the application name https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L82

**Comment by nil4** [comment]
PR #716 resolves this issue. /cc @davidfowl @Tratcher

**Comment by EricABC** [comment]
@davidfowl I see this gets an overhaul in the dev branch, but for the release is there any chance you might consider moving the _options.Application to the top of ResolveApplicationName for release (which closer matches the dev branch already)? [L265](https://github.com/aspnet/Hosting/blob/release/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L265).  The problem I encounter is when abstracting out some of the startup process for several apps with common configuration.  It ends up leading to somewhat cryptic routing 404's and 'view not found' in MVC because Build() will set the IHostingEnvironment ApplicationName based on a delegate living in a base type outside the entry assembly.  Because Build() always calls this first [here](https://github.com/aspnet/Hosting/blob/release/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L183) there is no way I can find to set the name to the actual entry assembly before HostingEnvironment.Initialize is called.  Its not that it can't be worked around, the but workarounds would be needed for each front end app.

Thanks for considering:)
