### ISSUE TITLE
IServerAddressesFeature Returns Wrong Port Under IIS Express

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Hosting#811]
I want to get the base URL that my app is running under, so I can register it with [Consul](https://www.consul.io/). I am doing this at application startup, so I can't use the URL from an incoming request. I have tried the following code running as a console app and IIS Express:

```
public void Configure(IApplicationBuilder application)
{
    var addresses = application.ServerFeatures.Get<IServerAddressesFeature>().Addresses;
    // Console returns http://*:5010
    // IIS Express returns http://localhost:5264/
    ...
}
```

My app is configured to run on port 5010. IIS Express seems to be returning a random port each time the app is started. Can the behaviour be explained?

**Comment by Tratcher** [comment]
That's not going to work for IIS or IIS Express.  IIS is running as a reverse proxy. It picks a random port for your process to listen on and does not flow the public address information to you.  The only way to get the public address information is from incoming requests.

**Comment by RehanSaeed** [comment]
@Tratcher Is there an alternative method of getting the address of a site or am I forced to manually provide the address as config.

**Comment by davidfowl** [comment]
You need to do it manually

**Comment by GuardRex** [comment]
This issue came up recently on Slack. I'd like to drop in the tinkering I did with PS to get the public port from IIS as a potential direction in case anyone stumbles in here looking for a way to get info from the reverse proxy IIS server.

This is only prototype code that was rattled off for a quick test (i.e., don't use this in production like this). This type of thing can be done in `Program > Main` to run at app startup ...
```
using System.Diagonistics;
...
var siteName = "testselfcontained";
ProcessStartInfo psi = new ProcessStartInfo();
psi.FileName = "powershell.exe";
psi.UseShellExecute = false;
psi.RedirectStandardOutput = true;
psi.Arguments = $"$webBinding = Get-WebBinding -Name '{siteName}';$port = $webBinding.bindinginformation.split(':')[1];Write-Host $port";
Process p  = Process.Start(psi);
var port = p.StandardOutput.ReadToEnd();
p.WaitForExit();
```
Setting the execution policy didn't work, so I had to elevate the AppPool's user identity to `Local System` to make it work.

If there are multiple bindings, then you'd have to add a little more PowerShell *cowbell* there to capture and parse out/return multiple ports.

Of course, I wanted to do this with PowerShell bits under `System.Management.Automation` for Core (https://github.com/PowerShell/PowerShell/releases). However, PS for Core is still alpha (as of 11/27/2016), and I ended up with dep conflicts in my 1.1/MSBuild test app (`1.0.0-preview3-004056`) when I tried to implement a test, but one could/should investigate this approach further ... https://github.com/PowerShell/PowerShell/issues/2291#issuecomment-250267238

NuGet.config:
`<add key="powershell.myget.org" value="https://powershell.myget.org/F/powershell-core" />`

csproj:
`<PackageReference Include="Microsoft.PowerShell.SDK" Version="6.0.0-alpha13" />`
```
string port;
using (PowerShell ps = PowerShell.Create())
{
    ps.AddScript($"$webBinding = Get-WebBinding -Name '{siteName}';$port = $webBinding.bindinginformation.split(':')[1];Write-Host $port");
    var result = ps.Invoke()[0];
    port = result.toString();
}
```
