### ISSUE TITLE
Enable hot patching scenario

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Hosting#823]
In the past, during RC1, when you publish, you won't be able to find .dll for the web application that you build. RTM use .dll like class library as the publish output.

Question is, how can we achieve patching and changing code while the web is running?

**Comment by davidfowl** [comment]
The application needs to be restarted.

**Comment by andrew-vandenbrink** [comment]
How to restart? Other than login to the server and restart via IIS

Any publish option to output the controller files instead to output it as dll?

**Comment by davidfowl** [comment]
> How to restart? Other than login to the server and restart via IIS

There's support for appoffline.htm. If you drop that file the app will restart.

> Any publish option to output the controller files instead to output it as dll?

Nope, deploy as source is gone.

**Comment by andrew-vandenbrink** [comment]
Problem with appoffline.htm, it's shutting down the website, how can I turn it on?
I need something else to delete the file.

Why it's being removed?
It was cool (and useful) that we can modify the our website while it's running

**Comment by muratg** [comment]
@andrew-vandenbrink Put the appoffline file to stop your site, update contents, remove the appofline file to restart your site.

**Comment by andrew-vandenbrink** [comment]
@muratg without login to my virtual machine, how to remove it? The site is down right.

The current situation makes me need to put more code in .cshtml view to make sure my website patchable

**Comment by muratg** [comment]
@andrew-vandenbrink. Let's roll back a little.  How do you even deploy your site?

**Comment by andrew-vandenbrink** [comment]
@muratg Login to the VM obviously but wordpress can update their version from the website, without login, ofcourse I know php is interpreted. 

Maybe I ask it in wrong place? There is "dotnet net run", but there is no "dotnet restart" or "dotnet update"

There is "dotnet build" but the output is only .dll :( 
https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build

Hey I just got idea,
I will upload the source code to private directory, call a ps script which will 
-put appoffline.htm
-call dotnet build
-remove appoffline.htm

will it work?

**Comment by GuardRex** [comment]
> "dotnet restart" or "dotnet update"

You're mixing CLI concepts with hosting concepts. Given the vast landscape of server hosting scenarios, it would be infeasible to attempt much beyond the tooling already provided (e.g., Web Deploy, FTP, etc.).

> -put appoffline.htm

If you go that direction, another option would be to stop and restart the app pool (for more along these lines, see https://github.com/GuardRex/aspnetcore-iis-ps-publish):
```powershell
# Stop the AppPool
if((Get-WebAppPoolState $webAppPoolName).Value -ne 'Stopped') {
    Stop-WebAppPool -Name $webAppPoolName
    while((Get-WebAppPoolState $webAppPoolName).Value -ne 'Stopped') {
        Start-Sleep -s 1
        # Could add a timeout here in case there is a problem
    }
}

# Work with the app here

# Start the AppPool
if((Get-WebAppPoolState $webAppPoolName).Value -ne 'Started') {
    Start-WebAppPool -Name $webAppPoolName
    while((Get-WebAppPoolState $webAppPoolName).Value -ne 'Started') {
        Start-Sleep -s 1
        # Could add a timeout here in case there is a problem
    }
}
```

**Comment by muratg** [comment]
@andrew-vandenbrink Did you consider using WebDeploy? No need to login to the VM.

**Comment by andrew-vandenbrink** [comment]
@muratg  no, no webDeploy or anything else
The user is no developer, a click of button should be able to upgrade the website

@GuardRex Website A call this powershell script which will makes website A, I think the powershell process will be also stopped, right?

**Comment by GuardRex** [comment]
> Website A call this powershell script which will makes website A, I think the powershell process will be also stopped, right?

I haven't had to do that myself, but I think that as long as you get it launched in a separate process, it should run regardless of what happens with the process under the AppPool. Take a look at using `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -file $path`, where `$path` is the path to the PowerShell script you want to run. You probably will need to add `-ExecutionPolicy ByPass` to it to bypass the execution policy. See if you can execute that within your app's code with `System.Diagnostics.Process.Start`. I don't know if that will work, but it's worth a shot. :gun: :smile:

If that doesn't work out, another alternative might be to use `System.Management.Automation`. If that also fails, check the PowerShell SDK and see if they have something that might work. I think they have a `RunspaceInvoke` piece to invoke scripts, but it might fail when the AppPool stops because it might be something that just runs on a thread on the same process as the AppPool. Anyway, it's worth a look if everything else goes nowhere.

**Comment by andrew-vandenbrink** [comment]
It's not working, any process called by my asp.net core application will be also killed once i stop asp.net core application. Please keep in mind that updating application will be triggered by user, not developers like us.

**Comment by GuardRex** [comment]
Could you run a script entirely independently of the apps then? When a user within their app triggers the app update, they're setting a flag in a queue or database that the control app is monitoring and acting upon. Since this control app is entirely independent of the user's app, it should be completely unaffected by the user's app state as it shuts it down, modifies it, and fires it back up.

**Comment by andrew-vandenbrink** [comment]
on RC
- Setup FTP server, overwrite all controllers, views, scripts, done!
- Without FTP also possible, edit the file directly, done!

on RTM
- Create 2 different sub domain, one is the application, one other to manage the application 
- Create windows service or cron jobs to update the application
Looks like a risk of security breach

**Comment by andrew-vandenbrink** [comment]
Old Asp.net mvc is hot patchable, asp.net core is NOT hot patchable which is a shame

Further discussion in 

https://github.com/aspnet/IISIntegration/issues/238
https://github.com/aspnet/KestrelHttpServer/issues/970

**Comment by andrew-vandenbrink** [comment]
In the end, I create updater and watcher (both console apps)

updater will create app_offline.htm
watcher will be notified if there is app_offline.htm and copy the whole update package and in the end will delete the app_offline.htm
