### ISSUE TITLE
Change webroot path in production environment

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Hosting#872]
In my development environment I have moved the `WebRoot` one level up from the `ContentRoot` using `.UseWebRoot(Path.Combine(Directory.GetCurrentDirectory(), "..", "dist"))`. When I use `dotnet publish` the `dist` directory is located on the same level as the `ContentRoot` alongside with the `Views` directory which means that the static files can not be found. Is this an issue or by design? If it's by design, how can I change `WebRoot` path depending on which environment I run on?

**Comment by davidfowl** [comment]
dotnet publish has no idea what you wrote in your `Program.cs`. You need to change it the `project.json` file accordingly so that when you publish files end up in the right location. What does your layout on disk look like? Are the static files outside of your project folder? Are you running on IIS or just using kestrel?

**Comment by marcuslindblom** [comment]
@davidfowl  I have changed my `project.json` to this:
```json
"publishOptions": {
    "include": [
      "../dist",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  }
```
... so my `dist` folder gets published but when I run the site using `dotnet run` the static files cannot be found because `Program.cs` points to a different `WebRoot`. Yes, the static files are placed outside the project folder. In my production environment I will use IIS.

**Comment by halter73** [comment]
[UseStaticFiles()](https://docs.asp.net/en/latest/fundamentals/static-files.html#serving-static-files) allows you to specify a FileProvider that can be configured to serve files from any path. You can have `UseStaticFiles()` only called in your [Startup.ConfigureDevelopment()](https://docs.asp.net/en/latest/fundamentals/environments.html#startup-conventions) method if you want to use IIS directly for static files in production.

If you use [mappings](https://github.com/aspnet/Announcements/issues/175#user-content-include-structure) instead of directly using include in your publish options, that can also give you a little more control in making your dev and prod directory layout different.

**Comment by marcuslindblom** [comment]
@halter73 @davidfowl I did some modifications to my `project.json` like this:

```c#
app.UseStaticFiles(new StaticFileOptions()
{
    FileProvider = new PhysicalFileProvider(
        Path.Combine(Directory.GetCurrentDirectory(), "..","..", "dist")),
            RequestPath = new PathString("/static")
});
```
but it seems like it's not possible to use static files from outside the `WebRoot` because I get a `404` when accessing any file in the `/static` folder?
If I use the configuration from the documentation page like this it's all fine and dandy:
```c#
app.UseStaticFiles(new StaticFileOptions()
{
    FileProvider = new PhysicalFileProvider(
        Path.Combine(Directory.GetCurrentDirectory(), @"MyStaticFiles")),
            RequestPath = new PathString("/static")
});
```
This is used in combination with the following startup class
```c#
public static void Main(string[] args)
{            
    var config = new ConfigurationBuilder()
        .AddCommandLine(args)
        .AddEnvironmentVariables(prefix: "ASPNETCORE_")
        .Build();

    var host = new WebHostBuilder()
        .UseConfiguration(config)
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())                
        .UseUrls("http://localhost:5000")
        .UseIISIntegration()
        .UseStartup<Startup>()

        .Build();

    host.Run();
}
```

**Comment by marcuslindblom** [comment]
@halter73 Thank you!
