### ISSUE TITLE
k web and k kestrel should give the url/port on the command line

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Hosting#89]
Today when ```k web``` or ```k kestrel``` are invoked the default output is simply ```Started```. It would be much better to include the url/port which was just started. W/o this users will need to look into ```project.json``` to figure out the port number.

**Comment by glennc** [comment]
This has been done, you can see the url and port if you have a console logger attached, which the default template does.

**Comment by flyandi** [comment]
Can someone explain why everything with Microsoft has to be so complicated. Why not just add a flag to see directly the console output or someone could just post a full description instead of cryptic answers. Lot's of people have issue and there is barely documentation available and people land here and find an uncompleted answer. You can't expect that everyone is involved in the core development of ASP.NET 5.0. Although promising it has been more than frustrating so far.
