### ISSUE TITLE
Ability to change EnvironmentName fields

### ISSUE THREAD

**Issue by abstract-christos** [aspnet/Hosting#923]
Hi there,
Is there any reason why the fields in Microsoft.AspNetCore.Hosting.EnvironmentName are readonly? It would simplify our deployment if we could use custom strings for the three environments and still be sure that all implementations that use the related extension methods would still work as intented.

**Comment by davidfowl** [comment]
We can design better ways to achieve this than by making public static readonly fields not read only. The problem is that we're using extension methods so there's no flexibility here. If this feature is something that people do often then we can look at alternative ways to build a mapping from actual environment variables to the more symbolic names "Development", "Staging" and "Production" etc. 

This isn't trivial because changing the default means that some of the tools like visual studio setting the environment to "Development" might be wrong (we could alllow multi mapping to fix this though).

For now, I suggest making your own extension methods for your special names.

**Comment by abstract-christos** [comment]
True. The problem is however that a lot of other 3rd party tools actually use the .IsDevelopment() extension and adjust their behaviour according to it. One example is https://github.com/aspnet/JavaScriptServices that relies on it in order to turn on or off debugging on the browser for example.
